In [4]:
# NumPy--> Numerical python

import numpy as np
bonus = 10
marks = np.array([55,90,40,70,80])

new_marks = marks + bonus
print(new_marks)


[ 65 100  50  80  90]


In [5]:
a = [ 4,6,8,2,1]
type(a)

list

In [6]:
print(a)

[4, 6, 8, 2, 1]


In [7]:
np_a= np.array(a)
print(np_a)

[4 6 8 2 1]


In [8]:
type(np_a)

numpy.ndarray

In [9]:
# given a python list:
a = [3,6,1,9]

In [10]:
import numpy as np
numbers = np.array([3,6,1,9])
print(numbers*2)

[ 6 12  2 18]


In [11]:
a_np= np.array([3,6,1,9])
print(a_np)

[3 6 1 9]


In [12]:
a_np+2

array([ 5,  8,  3, 11])

In [13]:
a_np

array([3, 6, 1, 9])

In [14]:
a_np/2

array([1.5, 3. , 0.5, 4.5])

In [15]:
b = [1,2,3,4,5.6]

In [16]:
import numpy as np
b_num= np.array([1,2,3,4,5,6])

In [17]:
print(b_num-2)

[-1  0  1  2  3  4]


In [18]:
print(b_num+2)

[3 4 5 6 7 8]


In [19]:
print(b_num*2)

[ 2  4  6  8 10 12]


In [20]:
print(b_num/2)

[0.5 1.  1.5 2.  2.5 3. ]


In [21]:
b_num

array([1, 2, 3, 4, 5, 6])

In [22]:
b_num+2

array([3, 4, 5, 6, 7, 8])

In [23]:
b_num-3

array([-2, -1,  0,  1,  2,  3])

In [24]:
b_num/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [25]:
b_num*2

array([ 2,  4,  6,  8, 10, 12])

In [26]:
a = [
    [2,4,5],
    [6,3,1],
    [5,7,2]
]
type(a)

list

In [27]:
print(a)

[[2, 4, 5], [6, 3, 1], [5, 7, 2]]


In [28]:
b = np.array(a)
print(b)

[[2 4 5]
 [6 3 1]
 [5 7 2]]


In [29]:
type(b)

numpy.ndarray

In [30]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [31]:
a = np.zeros((4,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [32]:
a = np.ones(4)
print(a)

[1. 1. 1. 1.]


In [34]:
a = np.ones((4,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [37]:
import numpy as np

a = np.arange(5)
print(a)

[0 1 2 3 4]


In [39]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [45]:
import numpy as np
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [46]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [47]:
type(a)

numpy.ndarray

In [49]:
a = np.arange(1,12)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [51]:
a = np.arange(1,10)
# To print only the even numbers, use boolean indexing:
print(a[a%2==0])

[2 4 6 8]


In [52]:
a = np.arange(1,11,2)
print(a)

[1 3 5 7 9]


In [54]:
a = np.arange(0,11,2)
print(a)

[ 0  2  4  6  8 10]


In [55]:
a = np.arange(2,11,2)
print(a)

[ 2  4  6  8 10]


In [56]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [58]:
np.arange(1,32)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [62]:
a = np.linspace(0,10,5)
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [65]:
np.linspace(3,10,5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [66]:
a = np.array([3,5,6])
b = np.array([5,6,1])

In [67]:
print(a)

[3 5 6]


In [68]:
print(b)

[5 6 1]


In [69]:
a+b

array([ 8, 11,  7])

In [70]:
print(a+b)

[ 8 11  7]


In [71]:
print(a-b)

[-2 -1  5]


In [72]:
print(b-a)

[ 2  1 -5]


In [73]:
print(a*b)

[15 30  6]


In [75]:
print(a**2)

[ 9 25 36]


In [76]:
print(b**2)

[25 36  1]


In [77]:
print(a**b)

[  243 15625     6]


In [78]:
print(a+5)

[ 8 10 11]


In [79]:
print(a-5)

[-2  0  1]


In [80]:
print(a*5)

[15 25 30]
