In [10]:
import numpy as np
a = np.array([4,3,1])
b = np.array([5,4,2])

In [11]:
a+b

array([9, 7, 3])

In [12]:
a-b

array([-1, -1, -1])

In [13]:
a*b

array([20, 12,  2])

In [14]:
# Given a list of prices, update them with gst included prices.
prices = [50,100,40,90,80]
np_prices= np.array(prices)
gst_np = np_prices*1.18
print(gst_np)

[ 59.  118.   47.2 106.2  94.4]


In [15]:
num = (4,6,3,1)
a = np.array(num)
print(a)

[4 6 3 1]


In [16]:
type(a)

numpy.ndarray

In [17]:
type(num)

tuple

In [18]:
a = np.array([5,4,5.5,9])
print(a)

[5.  4.  5.5 9. ]


In [19]:
names = np.array(["shivam","ayush","ankit","Rahul"])

In [20]:
print(names)

['shivam' 'ayush' 'ankit' 'Rahul']


In [21]:
type(names)

numpy.ndarray

In [22]:
len(names)

4

In [23]:
a = np.array([True,False,True])
print(a)

[ True False  True]


In [24]:
type(a)

numpy.ndarray

In [33]:
import numpy as np
marks = np.array([
    [70,80,90],
    [60,75,85]
])

In [34]:
marks[0,1]

np.int64(80)

In [27]:
marks[0][1]

np.int64(80)

In [28]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [30]:
np.ones(5)*5

array([5., 5., 5., 5., 5.])

In [31]:
np.full(6,2)

array([2, 2, 2, 2, 2, 2])

In [32]:
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [37]:
# 0-10 all even numbers:
# linspace,arrange
a = np.arange(0,11,2)
print(a)


[ 0  2  4  6  8 10]


In [40]:
b = np.linspace(0,10,6)
print(b)

[ 0.  2.  4.  6.  8. 10.]


In [41]:
print(b.dtype)

float64


In [42]:
print(a.dtype)

int64


In [43]:
a = np.array([True,False])
print(a.dtype)

bool


In [45]:
b= np.array([4,7,7,3])
print(b.dtype)

int64


In [46]:
a = np.array([10,20,30],dtype = float)
print(a)

[10. 20. 30.]


In [47]:
a.dtype

dtype('float64')

In [49]:
a = np.array([10.5,4.5,7],dtype=int)
print(a)

[10  4  7]


In [52]:
a = np.array([2,4,0,7,0],dtype=bool)
print(a)

[ True  True False  True False]


In [ ]:
# 0->False
# non-zero ->True

In [53]:
import numpy as np
marks = np.array([60,70,80,90,100])
bonus = marks+5
final_marks = bonus*1
print(marks)
print(bonus)
print(final_marks)

[ 60  70  80  90 100]
[ 65  75  85  95 105]
[ 65  75  85  95 105]


In [56]:
import numpy as np

numbers = [10,20,30]
list_result = numbers*2

arr = np.array(numbers)
array_result = arr*2

print(list_result)
print(array_result)

[10, 20, 30, 10, 20, 30]
[20 40 60]


In [59]:
import numpy as np

prices = np.array([100,200,300,400,500])
discount = prices*0.10
final_price = prices-discount

print(discount)
print(final_price)

[10. 20. 30. 40. 50.]
[ 90. 180. 270. 360. 450.]


In [60]:
import numpy as np

numbers = np.arange(2,21,3)
print(numbers)
print(numbers[0])
print(numbers[-1])
print(len(numbers))
print(numbers*2)

[ 2  5  8 11 14 17 20]
2
20
7
[ 4 10 16 22 28 34 40]


In [63]:
import numpy as np

values = np.linspace(0,20,5)
print(values)

doubled = values*2
print(doubled)

print(values+10)
print(values/2)

[ 0.  5. 10. 15. 20.]
[ 0. 10. 20. 30. 40.]
[10. 15. 20. 25. 30.]
[ 0.   2.5  5.   7.5 10. ]


In [62]:
import numpy as np

attendence = np.zeros(5)
print(attendence)

attendence = attendence+5
print(attendence)

attendence = attendence+3
print(attendence)

attendence = attendence*2
print(attendence)

[0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5.]
[8. 8. 8. 8. 8.]
[16. 16. 16. 16. 16.]


In [64]:
import numpy as np

salary = np.full(5,30000)
print(salary)

increment = salary*0.10
print(increment)

new_salary = salary + increment
print(new_salary)
print(new_salary*2)


[30000 30000 30000 30000 30000]
[3000. 3000. 3000. 3000. 3000.]
[33000. 33000. 33000. 33000. 33000.]
[66000. 66000. 66000. 66000. 66000.]


In [65]:
import numpy as np

arr = np.array([10,20,30.5,40,50])
print(arr)
print(arr.dtype)

result = arr*2
print(result)
print(result.dtype)

[10.  20.  30.5 40.  50. ]
float64
[ 20.  40.  61.  80. 100.]
float64


In [67]:
import numpy as np

marks = np.array([
    [70,80,90],
    [60,75,85]
])

print(marks)
print(marks + 5)
print(marks * 2)
print(marks - 10)

[[70 80 90]
 [60 75 85]]
[[75 85 95]
 [65 80 90]]
[[140 160 180]
 [120 150 170]]
[[60 70 80]
 [50 65 75]]


In [70]:
import numpy as np

a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

addition = a+b
subtraction = a-b
multiplication = a*b

print(addition)
print(subtraction)
print(multiplication)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]


In [73]:
import numpy as np

salary = np.array([30000,40000,50000,60000])
increment = salary *0.20
new_salary = salary + increment

print(salary)
print(increment)
print(new_salary)

bonus = new_salary * 0.05
print(bonus)

print(new_salary + bonus)


[30000 40000 50000 60000]
[ 6000.  8000. 10000. 12000.]
[36000. 48000. 60000. 72000.]
[1800. 2400. 3000. 3600.]
[37800. 50400. 63000. 75600.]


In [75]:
import numpy as np

numbers = np.arange(2,21,2)
print(numbers)

result = numbers+1
print(result)

result = result*2
print(result)

print(len(numbers))

[ 2  4  6  8 10 12 14 16 18 20]
[ 3  5  7  9 11 13 15 17 19 21]
[ 6 10 14 18 22 26 30 34 38 42]
10


In [76]:
import numpy as np

a = np.arange(0,11,2)
b = np.linspace(0,10,6)

print(a)
print(b)
print(a*2)
print(b*2)
print(len(a))
print(len(b))

[ 0  2  4  6  8 10]
[ 0.  2.  4.  6.  8. 10.]
[ 0  4  8 12 16 20]
[ 0.  4.  8. 12. 16. 20.]
6
6


In [77]:
import numpy as np

a = np.arange(0,11,2)
b = np.linspace(0,10,6)

print(a)
print(b)
print(a*2.0)
print(b*2)
print(len(a))
print(len(b))

[ 0  2  4  6  8 10]
[ 0.  2.  4.  6.  8. 10.]
[ 0.  4.  8. 12. 16. 20.]
[ 0.  4.  8. 12. 16. 20.]
6
6


In [78]:
import numpy as np

a = np.array([1,2,3])
b = np.array([1.5,2.5,3.5])

print(a.dtype)
print(b.dtype)

c = a+b
print(c)
print(c.dtype)

int64
float64
[2.5 4.5 6.5]
float64


In [79]:
import numpy as numpy

arr = np.array([10.5,20.7,30.9], dtype=int)

print(arr)
print(arr.dtype)

result = arr + 5
print(result)

print(result*2)

[10 20 30]
int64
[15 25 35]
[30 50 70]


In [80]:
import numpy as np

arr = np.array([0,1,2,0,5],dtype = bool)

print(arr)

result = arr*1
print(result)

result = result+5
print(result)

print(result.dtype)

[False  True  True False  True]
[0 1 1 0 1]
[5 6 6 5 6]
int64


In [81]:
import numpy as np

arr = np.zeros((3,4))

print(arr)
print(arr+10)
print(arr*5)
print(arr+100)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[100. 100. 100. 100.]
 [100. 100. 100. 100.]
 [100. 100. 100. 100.]]
