In [1]:
import numpy as np

arr = np.ones((2,3))
print(arr)

result = arr*10
print(result)

result = result+5
print(result)

result = result/5
print(result)

[[1. 1. 1.]
 [1. 1. 1.]]
[[10. 10. 10.]
 [10. 10. 10.]]
[[15. 15. 15.]
 [15. 15. 15.]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [2]:
import numpy as np

arr = np.full(4,50)
print(arr)

arr = arr+20
print(arr)

arr = arr*2
print(arr)

arr = arr-10
print(arr)


[50 50 50 50]
[70 70 70 70]
[140 140 140 140]
[130 130 130 130]


In [3]:
import numpy as np

celsius = np.array([0,10,20,30,40])
farenheit=(celsius*(9/5))+32
print(farenheit)


[ 32.  50.  68.  86. 104.]


In [4]:
# A student has scored:
# 65,72,80,88,91
# create a NumPy array containing these marks.
# Add 5 bonus marks to every subjects and display the original marks and update marks.

marks = np.array([65,72,80,88,91])
print(marks)
bonus = 5
print(marks+bonus)

[65 72 80 88 91]
[70 77 85 93 96]


In [5]:
# Ashop has five products with prices:
# 100,250,400,550,800
# create a numpy array
# and calculate the price after apply a 10% discount to every product.
price = np.array([100,250,400,550,800])
print("original prices",price)
discount = 0.10
final_price= (price-(price*discount))
print("Prices after discount",final_price)

original prices [100 250 400 550 800]
Prices after discount [ 90. 225. 360. 495. 720.]


In [6]:
# A company has 5 employees with salaries:
# 30000,35000,40000,45000,50000
# Create an array and give every employee a 10% salary increment.

salary = np.array([30000,35000,40000,45000,50000])
print(salary)
new_salary=(salary*1.10)
print(new_salary)


[30000 35000 40000 45000 50000]
[33000. 38500. 44000. 49500. 55000.]


In [7]:
salary = np.array([30000,35000,40000,45000,50000])
print(salary)
icrement = 0.10
new_salary = (salary+salary*0.10)
print(new_salary)

[30000 35000 40000 45000 50000]
[33000. 38500. 44000. 49500. 55000.]


In [8]:
# A sudent's marks are stored in a touple:
# (78,85,92,67,88)
# convert the touple into a numpy array and add 3 marks to every value.

marks = ((78,85,92,67,88))
np_marks = np.array(marks)
print(np_marks+3)

[81 88 95 70 91]


In [9]:
# A company records sales for four quarters:
# Q1 = 125000
# Q2 = 148000
# Q3 = 135000
# Q4 = 172000

# create a NumPy array.
# the company expects next year's sales to be 15% higher than this year's sales.
# Calculate the expected sales for each.
# Then calculate the additional sales expected in each quarter.

In [11]:
sales = np.array([125000,148000,135000,172000])
next_sales = sales*1.15
print(next_sales)
print(.15*sales)

[143750. 170200. 155250. 197800.]
[18750. 22200. 20250. 25800.]


In [13]:
# Two brances of a company have inventory for 5 products.
#  Branch A = [120,150,180,100,200]
#  Branch B = [80,130,170,120,250]

#  Create Two NumPy arrays.

#  calculate:

#  Total inventory for each product.
#  Difference between branch A and branch B.
#  Combine inventory after receiving an additional 20 units for every product.

BranchA =np.array([120,150,180,100,200])
BranchB = np.array([80,130,170,120,250])

print("Total inventory",BranchA+BranchB)
print("Difference",BranchA-BranchB)
print("Additional 20 units",BranchA+BranchB+20)


Total inventory [200 280 350 220 450]
Difference [ 40  20  10 -20 -50]
Additional 20 units [220 300 370 240 470]


In [14]:
# A stores sells four products.

# prices:

# [250,400,750,1200]

# Units sold:
# [12,8,5,10]

# calculate the revenue generated by each product.

# The store then wants to increase the revenue figures by 5% for forecasting purposes.

prices = np.array([250,400,750,1200])
units = np.array([12,8,5,10])

print("Generated revenue",prices*units)
print("Forecast",(prices*units)*0.05+(prices*units))

Generated revenue [ 3000  3200  3750 12000]
Forecast [ 3150.   3360.   3937.5 12600. ]


In [15]:
marks = np.array([45,87,67,90])
print(marks)

[45 87 67 90]


In [17]:
arr = np.array([
    [80,75,90],
    [70,85,88],
    [92,90,85]
])
print(arr)

[[80 75 90]
 [70 85 88]
 [92 90 85]]


In [18]:
marks.ndim

1

In [19]:
arr.ndim

2

In [21]:
a = np.array([
    [[1,2],
     [3,4]
    ],
    [
       [5,6],
       [7,8]
    ]
])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
a.ndim

3

In [28]:
a.shape

(2, 2, 2)

In [24]:
marks.shape #no of rows and columns

(4,)

In [25]:
arr.shape

(3, 3)

In [27]:
arr.size #number of elements

9

In [29]:
marks.size

4

In [30]:
len(arr) #no of elem in outer bracket

3

In [31]:
len(a)

2

In [33]:
arr = np.array([10.5,20.7,30.9])
arr_int = arr.astype(int)
print(arr)
print(arr_int)

[10.5 20.7 30.9]
[10 20 30]


In [35]:
arr = np.array([10.5,20.7,30.9],dtype=int)
print(arr)     #convert original aaray

[10 20 30]


In [36]:
data = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,100,110,120]

])

print("len",len(data))
print("size",data.size)
print("shape",data.shape)
print("ndim",data.ndim)

len 3
size 12
shape (3, 4)
ndim 2


In [39]:
student_marks = np.array([
    [78,85,90,88,76],
    [92,81,85,89,95],
    [67,72,70,75,68],
    [88,91,94,90,87],
    [76,80,79,82,85]
])

print(student_marks)
print("Number of dimensions =",student_marks.ndim)
print("Shape =",student_marks.shape)
print("Total number of values =",student_marks.size)
print("Data type =",student_marks.dtype)
print("Number of students =", student_marks.shape[0])
print("Number of subjects =", student_marks.shape[1])

[[78 85 90 88 76]
 [92 81 85 89 95]
 [67 72 70 75 68]
 [88 91 94 90 87]
 [76 80 79 82 85]]
Number of dimensions = 2
Shape = (5, 5)
Total number of values = 25
Data type = int64
Number of students = 5
Number of subjects = 5


In [42]:
# A collage wants to initialize a marks table for 5 students and 4 subjects.student_marks

# Initially, every student's marks are set to zero.

# create this using NumPy.

# Then create another 5 * 4 array containg a default value of 50.

marks = np.zeros((5,4))
print(marks)

new_marks = np.full((5,4),50)
print(new_marks)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]]


In [44]:
# Five students have scores:

# [45,56,67,78,89]

# The teacher gives everyone 3 grace marks.

# After that, the collage applies a 10% scaling factor to the adjusted scores.

# calculate the final scores.

marks = np.array([45,56,67,78,89])
grace_marks = 3
scalling_factor = (marks+grace_marks)*0.10
final_score = (marks+grace_marks)+(marks+grace_marks)*0.10
print(final_score)

[ 52.8  64.9  77.   89.1 101.2]


In [45]:
# A comapny wants to targets from 20,000 to 1,00,000.

#  Generate only 9 target values, equally spaced.

#  Then create actual sales:

#  [18000,28000,39000,47000,57000,66000,76000,90000,105000]

#  Calculate the difference between actual and target.

target = np.linspace(20000,100000,9)

actual_sales = np.array([18000,28000,39000,47000,57000,66000,76000,90000,105000])

difference = actual_sales-target

print("Target",target)
print("Actual",actual_sales)
print("Difference",difference)

Target [ 20000.  30000.  40000.  50000.  60000.  70000.  80000.  90000. 100000.]
Actual [ 18000  28000  39000  47000  57000  66000  76000  90000 105000]
Difference [-2000. -2000. -1000. -3000. -3000. -4000. -4000.     0.  5000.]


In [48]:
import numpy as np

# A dataset contains:

# [10,20,30.5,40,50.75]

# Create a NumPy array and display its data type.

# Then create an integer version of the array.

# finally, multiply the integer array by 3.

dataset = np.array([10,20,30.5,40,50.75])
print(dataset.dtype)
integer_dataset = dataset.astype(np.int64)
print(integer_dataset)
print(integer_dataset*3)

float64
[10 20 30 40 50]
[ 30  60  90 120 150]


In [52]:
# A company has product price:

# [499,799,1299,1999,2499]

# The company wants to:

# Increase all prices by 12%.
# Add 50 packing charges.
# calculate the final customer price.

prices = np.array([499,799,1299,1999,2499])
print("Increased price =",prices*1.12)
print(" 50 packing charge =",prices*1.12+50)
final_customer_price = prices*1.12+50
print("final_customer_price",final_customer_price)

Increased price = [ 558.88  894.88 1454.88 2238.88 2798.88]
 50 packing charge = [ 608.88  944.88 1504.88 2288.88 2848.88]
final_customer_price [ 608.88  944.88 1504.88 2288.88 2848.88]
