In [1]:
import numpy as np
marks = np.array([70,80,65,90,75])
print(marks.dtype)
print(marks.ndim)
print(marks.shape)
print(marks.size)

int64
1
(5,)
5


In [2]:
marks[0]

np.int64(70)

In [3]:
marks[3]

np.int64(90)

In [4]:
marks[2]

np.int64(65)

In [5]:
marks

array([70, 80, 65, 90, 75])

In [6]:
# print all the numpy array sepreated by a space.
print(marks, end=" ")

[70 80 65 90 75] 

In [7]:
n = len(marks)
for i in range(n):
  print(marks[i],end = " ")

70 80 65 90 75 

In [8]:
n= len(marks)
print(marks[n-1])

75


In [9]:
print(marks[-1])

75


In [10]:
print(marks[n-2])

90


In [11]:
print(marks[-2])

90


In [12]:
print(marks)

[70 80 65 90 75]


In [13]:
marks[2]=marks[2]+5

In [14]:
print(marks)

[70 80 70 90 75]


In [15]:
marks = marks+5

In [16]:
print(marks)

[75 85 75 95 80]


In [17]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
2
(3, 3)
9
int64


In [18]:
print(arr[0][2])

30


In [19]:
arr[0,2]

np.int64(30)

In [20]:
print(arr[0,2])

30


In [21]:
print(arr[1,1])

50


In [22]:
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [23]:
# Print all the digonal elements of the 2nd np array.
np.diagonal(arr)

array([10, 50, 90])

In [24]:
# A college stores marks of 4 students in 3 subjects: Maths, Science, and English

# import numpy as np

# marks = np.array([
#  [72,85,90],
#  [65,78,82],
#  [88,91,84],
#  [70,76,80]
# ])

# Perform the following:

# Display the marks of the third student.
# Display the Science marks of the second student.
# Add 5 bonus marks to every student's English marks.
# Change the Maths marks of the fourth student to 75.
# Display the final marks array.

In [25]:
marks = np.array([
  [72,85,90],
  [65,78,82],
  [88,91,84],
  [70,76,80]
 ])

In [26]:
# Display the marks of the third student.
print(marks[2])

[88 91 84]


In [27]:
# Display the Science marks of the second student.
print(marks[1,1])

78


In [28]:
# Add 5 bonus marks to every student's English marks.
marks[:,2] = marks[:,2]+5

In [29]:
marks

array([[72, 85, 95],
       [65, 78, 87],
       [88, 91, 89],
       [70, 76, 85]])

In [30]:
# Change the Maths marks of the fourth student to 75.
marks[3,0]=75

In [31]:
print(marks)

[[72 85 95]
 [65 78 87]
 [88 91 89]
 [75 76 85]]


In [32]:
# Display the final marks array.
print(marks)

[[72 85 95]
 [65 78 87]
 [88 91 89]
 [75 76 85]]


In [33]:
# A company records monthly sales for 3 branches. The columns represent January, February, and March.

# import numpy as np

# sales = np.array([
#     [120,150,180],
#     [100,130,160],
#     [200, 220, 250]
# ])

# Perform the following:

# Display the complete sales data of Branch 2.
# Display the sales of all branches in February.
# Increase the March sales of every branch by 10%.
# The January sales of Branch 1 were entered incorrectly. Change them from 120 to 135.
# Display the updated sales array.


In [34]:
sales = np.array([
     [120,150,180],
     [100,130,160],
     [200, 220, 250]
 ])

In [35]:
# Display the complete sales data of Branch 2.
print(sales[1])

[100 130 160]


In [36]:
# Display the sales of all branches in February.
print(sales[:,1])

[150 130 220]


In [37]:
# Increase the March sales of every branch by 10%.
sales[:,2] = 1.1* (sales[:,2])

In [38]:
print(sales)

[[120 150 198]
 [100 130 176]
 [200 220 275]]


In [39]:
# The January sales of Branch 1 were entered incorrectly. Change them from 120 to 135.
sales[0,0] = 135

In [40]:
print(sales)

[[135 150 198]
 [100 130 176]
 [200 220 275]]


In [41]:
# Display the updated sales array.
print(sales)

[[135 150 198]
 [100 130 176]
 [200 220 275]]


In [41]:
# An organization stores employee information as:
# Salary | Experience
# import numpy as np
# employees = np.array([
# [30000, 2],
# [40000, 4],
# [50000, 6],
# [60000, 8]
# ])
# Perform the following:
# Display the information of the last employee using negative indexing.
# Display the salary of the second employee.
# Increase the salary of the third employee by 15%.
# Add 1 year of experience to the first employee.
# Display the final employee array.

In [42]:
import numpy as np
employees = np.array([
 [30000, 2],
 [40000, 4],
 [50000, 6],
 [60000, 8]
 ])

In [43]:
# Display the information of the last employee using negative indexing.
print(employees[-1])

[60000     8]


In [44]:
# Display the salary of the second employee.
print(employees[1,0])

40000


In [45]:
# Increase the salary of the third employee by 15%.
employees[2,0] = 1.15*employees[2,0]

In [ ]:
employees[2,0]*=1.15

In [46]:
print(employees)

[[30000     2]
 [40000     4]
 [57499     6]
 [60000     8]]


In [52]:
# Add 1 year of experience to the first employee.
employees[0,1] = employees[0,1]+1

In [53]:
print(employees)

[[30000     3]
 [40000     4]
 [57499     6]
 [60000     8]]


In [54]:
# Display the final employee array.
print(employees)

[[30000     3]
 [40000     4]
 [57499     6]
 [60000     8]]


In [ ]:
# A company has inventory information for 4 products across 3 warehouses.
# Columns: Warehouse A, Warehouse B, Warehouse C
# import numpy as np
# inventory = np.array([
# [100, 120, 150],
# [80, 90, 110],
# [200, 180, 160],
# [50, 70, 90]
# ])
# Perform the following:
# Display the inventory of Product 3 across all warehouses.
# Display the inventory of Warehouse B for all products.
# Warehouse A receives 20 additional units of every product. Update the array.
# The inventory of Product 4 in Warehouse C is incorrect. Change it to 100.
# Display the final inventory.

In [65]:
import numpy as np
inventory = np.array([
 [100, 120, 150],
 [80, 90, 110],
 [200, 180, 160],
 [50, 70, 90]
 ])

In [66]:
# Display the inventory of Product 3 across all warehouses.
print(inventory[2])

[200 180 160]


In [67]:
# Display the inventory of Warehouse B for all products.
print(inventory[:,1])

[120  90 180  70]


In [68]:
# Warehouse A receives 20 additional units of every product. Update the array.
inventory[:,0]+=20
print(inventory)

[[120 120 150]
 [100  90 110]
 [220 180 160]
 [ 70  70  90]]


In [69]:
# The inventory of Product 4 in Warehouse C is incorrect. Change it to 100.
inventory[3,2]=100
print(inventory)

[[120 120 150]
 [100  90 110]
 [220 180 160]
 [ 70  70 100]]


In [70]:
# Display the final inventory.
print(inventory)

[[120 120 150]
 [100  90 110]
 [220 180 160]
 [ 70  70 100]]


In [ ]:
# A weather application stores temperatures for 3 cities.
# Columns: Morning, Afternoon, Evening
# import numpy as np
# temperature = np.array([
# [24, 35, 28],
# [22, 32, 26],
# [27, 38, 30]
# ])
# Perform the following:
# Display the complete temperature data of the first city.
# Display all afternoon temperatures.
# Display the evening temperature of the last city using negative indexing.
# Increase all morning temperatures by 2°C.
# The afternoon temperature of the second city was recorded incorrectly. Change it from 32 to 34.
# Display the final temperature array.


In [71]:
import numpy as np
temperature = np.array([
 [24, 35, 28],
 [22, 32, 26],
 [27, 38, 30]
 ])

In [74]:
# Display the complete temperature data of the first city.
print(temperature[0,:])

[24 35 28]


In [75]:
# Display all afternoon temperatures.
print(temperature[:,1])

[35 32 38]


In [77]:
# Increase all morning temperatures by 2°C.
temperature[:,0] +=2
print(temperature)

[[26 35 28]
 [24 32 26]
 [29 38 30]]


In [78]:
# The afternoon temperature of the second city was recorded incorrectly. Change it from 32 to 34.
temperature[1,1] = 34
print(temperature)

[[26 35 28]
 [24 34 26]
 [29 38 30]]


In [82]:
# Display the evening temperature of the last city using negative indexing.
temperature[-1,-1]

np.int64(30)

In [83]:
temperature[-1,2]

np.int64(30)

In [84]:
# Display the final temperature array.
print(temperature)


[[26 35 28]
 [24 34 26]
 [29 38 30]]
