In [1]:
import numpy as np

marks = np.array([70,80,65,90,75])

print(marks[0])
print(marks[2])
print(marks[-1])

70
65
75


In [2]:
print(marks[0:2])

[70 80]


In [3]:
print(marks[2:4])

[65 90]


In [4]:
# Find the elements of even indexes.
marks[0:5:2]


array([70, 65, 75])

In [5]:
marks[:3]

array([70, 80, 65])

In [6]:
marks[1:]

array([80, 65, 90, 75])

In [7]:
marks[::]

array([70, 80, 65, 90, 75])

In [8]:
marks[::2]

array([70, 65, 75])

In [9]:
marks

array([70, 80, 65, 90, 75])

In [10]:
marks[1:6:2]

array([80, 90])

In [11]:
number = np.array([10,20,30,40,50,60,70])
print(number[1:4])
print(number[2:6])
print(number[0:3])

[20 30 40]
[30 40 50 60]
[10 20 30]


In [12]:
number = np.array([10,20,30,40,50])
print(number[2:])

[30 40 50]


In [13]:
sales = np.array([100,150,200,250,300,350])
print(sales[-3:])

[250 300 350]


In [14]:
print(sales[:-2])

[100 150 200 250]


In [15]:
numbers = np.array([10,20,30,40,50,60])
print(numbers[::3])

[10 40]


In [16]:
numbers = np.array([10,20,30,40,50])
print(numbers[::-1])

[50 40 30 20 10]


In [17]:
marks = np.array([
    [70,80,90,85],
    [60,75,85,88],
    [88,92,95,90],
    [65,70,80,75]
])

In [18]:
print(marks[:2])

[[70 80 90 85]
 [60 75 85 88]]


In [19]:
print(marks[2:4])

[[88 92 95 90]
 [65 70 80 75]]


In [20]:
print(marks[1:3])

[[60 75 85 88]
 [88 92 95 90]]


In [21]:
print(marks[:,:2])

[[70 80]
 [60 75]
 [88 92]
 [65 70]]


In [22]:
print(marks[:,-2:])

[[90 85]
 [85 88]
 [95 90]
 [80 75]]


In [23]:
print(marks[1:3, 1:3])

[[75 85]
 [92 95]]


In [24]:
sales = np.array([
    [100,120,150,180],
    [200,220,250,270],
    [150,170,190,210]
])

In [25]:
print(sales[:,1:3]*1.10)

[[132. 165.]
 [242. 275.]
 [187. 209.]]


In [26]:
prices = np.array([
    1000,1500,2000,2500,3000,3500
])
# products 3-5 receive a 10% discount
prices[3:6] = prices[3:6]*0.90
print(prices)

[1000 1500 2000 2250 2700 3150]


In [27]:
# A company has recorded its monthly revenue for the first 6 months:

# import numpy as np

# revenue = np.array([120000,135000,142000,150000,165000,172000])

# Write a numpy program to:

# Display the revenue of the third month.
# Dispaly thr revenue of the last month using negative indexing.
# select the revenew from month 2 to month 5 using slicing.
# Increase the revenue of the last 3 months by 10%.
# Display the final revenue array.

In [28]:
revenue = np.array([120000,135000,142000,150000,165000,172000])

In [29]:
# Display the revenue of the third month.
print(revenue[2])

142000


In [30]:
# Dispaly thr revenue of the last month using negative indexing.
print(revenue[-1])

172000


In [31]:
# select the revenew from month 2 to month 5 using slicing.
print(revenue[2:6])

[142000 150000 165000 172000]


In [32]:
# Increase the revenue of the last 3 months by 10%.
revenue[-3:] = revenue[-3:]*1.10
print(revenue)

[120000 135000 142000 165000 181500 189200]


In [33]:
# Display the final revenue array.
print(revenue)

[120000 135000 142000 165000 181500 189200]


In [35]:
# A store has the following product prices:

# prices = np.array([500, 750, 1200, 1500, 2000, 2500])

# Write a program to:

# Display the first three prices.
# Display the last two prices.
# Apply a 15% discount only to products at indexes 2 through 4.
# Add ₹50 to the price of the first product.
# Display the updated prices.

In [34]:
prices = np.array([500, 750, 1200, 1500, 2000, 2500])


In [38]:
# Display the first three prices.
print(prices[0:3])

[ 500  750 1200]


In [39]:
# Display the last two prices.
print(prices[-2:])

[2000 2500]


In [40]:
# Apply a 15% discount only to products at indexes 2 through 4.
prices[2:5] = prices[2:5]*0.85
print(prices)


[ 500  750 1020 1275 1700 2500]


In [41]:
# Add ₹50 to the price of the first product.
prices[0] = prices[0]+50
print(prices)

[ 550  750 1020 1275 1700 2500]


In [42]:
# Display the updated prices.
print(prices)

[ 550  750 1020 1275 1700 2500]


In [43]:
# An electricity company wants to estimate the monthly electricity consumption
# of a household for 6 months.

# The expected consumption is:

# [180, 220, 195, 250, 280, 240] units.

# The company expects consumption to increase by 8% during the next billing cycle.

# Tasks

# Create a NumPy array for the consumption.
# Find the consumption in the 4th month.
# Extract the consumption of the last 3 months.
# Create a new array containing the expected consumption after an 8% increase.

In [59]:
# Create a NumPy array for the consumption.
import numpy as np
consumptions = np.array([[180, 220, 195, 250, 280, 240]])

In [53]:
print(consumptions[0, 3])

250


In [56]:
# Extract the consumption of the last 3 months.
print(consumptions[0, -3:])


[250 280 240]


In [60]:
# Create a new array containing the expected consumption after an 8% increase.
consumptions = consumptions*1.08
print(consumptions)


[[194.4 237.6 210.6 270.  302.4 259.2]]


In [ ]:
# A factory operates for 30 days and wants to create a production schedule
# starting from 500 units per day and gradually increasing to 1,500 units per day.

# Tasks
# Generate exactly 30 production targets using np.linspace().
# Create day numbers from 1 to 30 using np.arange().
# Display the first 5 production targets.
# Display the last 5 production targets.
# Increase every production target by 10%.
# Display the first 5 updated targets.

In [62]:
# Generate exactly 30 production targets using np.linspace().
target = np.linspace(500,1500,30)
print(target)

[ 500.          534.48275862  568.96551724  603.44827586  637.93103448
  672.4137931   706.89655172  741.37931034  775.86206897  810.34482759
  844.82758621  879.31034483  913.79310345  948.27586207  982.75862069
 1017.24137931 1051.72413793 1086.20689655 1120.68965517 1155.17241379
 1189.65517241 1224.13793103 1258.62068966 1293.10344828 1327.5862069
 1362.06896552 1396.55172414 1431.03448276 1465.51724138 1500.        ]


In [65]:
# Create day numbers from 1 to 30 using np.arange().
days = np.arange(1,31)
print(days)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [68]:
# Display the first 5 production targets.
print(target[0:5])

[500.         534.48275862 568.96551724 603.44827586 637.93103448]


In [69]:
# Display the last 5 production targets.
print(target[-5:])

[1362.06896552 1396.55172414 1431.03448276 1465.51724138 1500.        ]


In [70]:
# Increase every production target by 10%.
target = target*1.10
print(target)

[ 550.          587.93103448  625.86206897  663.79310345  701.72413793
  739.65517241  777.5862069   815.51724138  853.44827586  891.37931034
  929.31034483  967.24137931 1005.17241379 1043.10344828 1081.03448276
 1118.96551724 1156.89655172 1194.82758621 1232.75862069 1270.68965517
 1308.62068966 1346.55172414 1384.48275862 1422.4137931  1460.34482759
 1498.27586207 1536.20689655 1574.13793103 1612.06896552 1650.        ]


In [71]:
# Display the first 5 updated targets.
print(target[0:5])

[550.         587.93103448 625.86206897 663.79310345 701.72413793]


In [ ]:
# A college records marks of 5 students in 4 subjects.

# marks = np.array([
#     [72, 85, 90, 78],
#     [65, 70, 75, 80],
#     [88, 92, 95, 90],
#     [55, 65, 60, 70],
#     [78, 82, 85, 88]
# ])

# Each row represents a student and each column represents a subject.

# Tasks
# Determine the number of dimensions.
# Determine the number of students and subjects using shape.
# Determine the total number of marks using size.
# Display the complete marks of the 3rd student.
# Display marks of all students in the 2nd subject.
# Extract marks of the first 3 students in the first 2 subjects.
# Increase the marks of the last 2 students in the 4th subject by 5.

In [72]:
marks = np.array([
    [72, 85, 90, 78],
    [65, 70, 75, 80],
    [88, 92, 95, 90],
    [55, 65, 60, 70],
    [78, 82, 85, 88]
])

In [73]:
# Determine the number of dimensions.
print(marks.ndim)

2


In [74]:
# Determine the number of students and subjects using shape.
print(marks.shape)

(5, 4)


In [75]:
# Determine the total number of marks using size.
print(marks.size)

20


In [76]:
# Display the complete marks of the 3rd student.
print(marks[2])

[88 92 95 90]


In [77]:
# Display marks of all students in the 2nd subject.
print(marks[:,1])

[85 70 92 65 82]


In [78]:
# Extract marks of the first 3 students in the first 2 subjects.
print(marks[0:3,0:2])

[[72 85]
 [65 70]
 [88 92]]


In [79]:
# Increase the marks of the last 2 students in the 4th subject by 5.
marks[-2:,3]+=5
print(marks)

[[72 85 90 78]
 [65 70 75 80]
 [88 92 95 90]
 [55 65 60 75]
 [78 82 85 93]]


In [ ]:
# A restaurant stores prices of 6 menu items:

# prices = np.array([120, 180, 250, 300, 450, 600])

# The restaurant wants to run different pricing experiments.

# Tasks
# Add ₹20 to the first two items.
# Give a 10% discount to items 3, 4 and 5.
# Keep the last item unchanged.
# Display the first 3 prices after modification.
# Display the last 2 prices.

In [87]:
prices = np.array([120, 180, 250, 300, 450, 600])

In [82]:
# Add ₹20 to the first two items.
prices[0:2]+=20
print(prices)

[140 200 250 300 450 600]


In [89]:
# Give a 10% discount to items 3, 4 and 5.
prices[2:5] = prices[2:5]*0.90
print(prices)

[120 180 225 270 405 600]


In [ ]:
# Keep the last item unchanged.

In [91]:
# Display the first 3 prices after modification.
print(prices[0:3])

[120 180 225]


In [93]:
# Display the last 2 prices.
print(prices[-2:])

[405 600]


In [ ]:
# A machine records temperature every hour:

# temperature = np.array([
#     28, 29, 30, 31, 33, 35,
#     36, 35, 34, 32, 30, 29
# ])

# Tasks
# Extract readings from the first 6 hours.
# Extract readings from the last 6 hours.
# Extract readings from every alternate hour.
# Extract readings from every third hour.
# Reverse the complete temperature sequence.
# Extract the last 4 readings in reverse order.

In [94]:
temperature = np.array([
    28, 29, 30, 31, 33, 35,
    36, 35, 34, 32, 30, 29
])

In [95]:
# Extract readings from the first 6 hours.
print(temperature[:6])

[28 29 30 31 33 35]


In [96]:
# Extract readings from the last 6 hours.
print(temperature[-6:])

[36 35 34 32 30 29]


In [98]:
# Extract readings from every alternate hour.
print(temperature[0:12:2])

[28 30 33 36 34 30]


In [99]:
# Extract readings from every third hour.
print(temperature[0:12:3])

[28 31 36 32]


In [100]:
# Reverse the complete temperature sequence.
print(temperature[::-1])

[29 30 32 34 35 36 35 33 31 30 29 28]


In [104]:
# Extract the last 4 readings in reverse order.
print(temperature[-4:][::-1])

[29 30 32 34]


In [105]:
print(temperature[-1:-5:-1])

[29 30 32 34]


In [101]:
print(temperature.shape)

(12,)


In [102]:
print(temperature.size)

12
