In [ ]:
# A warehouse has 4 storage sections and 5 products.
# Initially, every product has a stock level of 100 units.
# Tasks

# Create a 4 × 5 array where every value is 100.

# Increase the stock of the first two sections by 20 units.

# Reduce stock of the last two products by 10%.

# Display only the middle two sections.

# Display only the first three products.

# Display the bottom-right 2 × 2 portion of the matrix.

In [2]:
# Create a 4 × 5 array where every value is 100.
import numpy as np
wherehouse = np.full((4,5),100)
print(wherehouse)

[[100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [3]:
# Increase the stock of the first two sections by 20 units.
wherehouse[0:2]+=20
print(wherehouse)

[[120 120 120 120 120]
 [120 120 120 120 120]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [5]:
# Reduce stock of the last two products by 10%.
wherehouse[:,-2:]=wherehouse[:,-2:]*0.90
print(wherehouse)

[[120 120 120 108 108]
 [120 120 120 108 108]
 [100 100 100  90  90]
 [100 100 100  90  90]]


In [7]:
# Display only the middle two sections.
print(wherehouse[1:3,:])

[[120 120 120 108 108]
 [100 100 100  90  90]]


In [8]:
# Display only the first three products.
print(wherehouse[:,:3])

[[120 120 120]
 [120 120 120]
 [100 100 100]
 [100 100 100]]


In [9]:
wherehouse

array([[120, 120, 120, 108, 108],
       [120, 120, 120, 108, 108],
       [100, 100, 100,  90,  90],
       [100, 100, 100,  90,  90]])

In [10]:
# Display the bottom-right 2 × 2 portion of the matrix.
print(wherehouse[-2:,-2:])

[[90 90]
 [90 90]]


In [12]:
# A company has salary for data for 4 employees:
# salary = np.array([
#     [30000, 5000],
#     [40000, 6000],
#     [50000, 8000],
#     [60000, 10000]
# ])
# Column 1 = Basic Salary

# Column 2 = Allowance
# Tasks

# Display the complete information of the 2nd employee.

# Display all basic salaries.

# Display all allowances.

# Increase all allowances by ₹1,000.

# Increase the basic salary of the last two employees by 10%.

# Display the final salary matrix.

In [13]:
salary = np.array([
    [30000, 5000],
    [40000, 6000],
    [50000, 8000],
    [60000, 10000]
])

In [14]:
# Display the complete information of the 2nd employee.
print(salary[1])


[40000  6000]


In [15]:
# Display all basic salaries.
print(salary[:,0])

[30000 40000 50000 60000]


In [17]:
# Display all allowances.
print(salary[:,1])

[ 5000  6000  8000 10000]


In [18]:
# Increase all allowances by ₹1,000.
salary [:,1]+=1000
print(salary)

[[30000  6000]
 [40000  7000]
 [50000  9000]
 [60000 11000]]


In [26]:
# Increase the basic salary of the last two employees by 10%.

salary[-2:,0]=salary[-2:,0]*1.10
print(salary)

[[30000  6000]
 [40000  7000]
 [55000  9000]
 [66000 11000]]


In [27]:
# Display the final salary matrix.
print(salary)

[[30000  6000]
 [40000  7000]
 [55000  9000]
 [66000 11000]]


In [28]:

# A startup expects its monthly users to grow from 10,000 to 100,000 over 12 months.

# Tasks

# Generate monthly user targets using np.linspace().

# Create month numbers using np.arange().

# Display users expected in Month 1 and Month 12.

# Display users expected from Months 4–8.

# Increase all targets by another 15%.

# Display the updated targets for the last 4 months.

In [39]:
# 1. Generate monthly user targets using np.linspace()
# From 10,000 to 100,000 over 12 months
users = np.linspace(10000, 100000, 12)
print("Monthly user targets:")
print(users)
print()

Monthly user targets:
[ 10000.          18181.81818182  26363.63636364  34545.45454545
  42727.27272727  50909.09090909  59090.90909091  67272.72727273
  75454.54545455  83636.36363636  91818.18181818 100000.        ]



In [40]:
# 2. Create month numbers using np.arange()
months = np.arange(1, 13)
print("Month numbers:")
print(months)
print()

Month numbers:
[ 1  2  3  4  5  6  7  8  9 10 11 12]



In [41]:
# 3. Display users expected in Month 1 and Month 12
print("Users in Month 1 and Month 12:")
print(users[0], users[11])          # or users[[0, 11]]
print()

Users in Month 1 and Month 12:
10000.0 100000.0



In [42]:
# 4. Display users expected from Months 4–8
print("Users from Months 4 to 8:")
print(users[3:8])                   # indices 3 to 7 (Months 4 to 8)
print()

Users from Months 4 to 8:
[34545.45454545 42727.27272727 50909.09090909 59090.90909091
 67272.72727273]



In [43]:
# 5. Increase all targets by another 15%
users = users * 1.15
print("Updated targets after +15%:")
print(users)
print()

Updated targets after +15%:
[ 11500.          20909.09090909  30318.18181818  39727.27272727
  49136.36363636  58545.45454545  67954.54545455  77363.63636364
  86772.72727273  96181.81818182 105590.90909091 115000.        ]



In [44]:
# 6. Display the updated targets for the last 4 months
print("Updated targets for the last 4 months:")
print(users[-4:])

Updated targets for the last 4 months:
[ 86772.72727273  96181.81818182 105590.90909091 115000.        ]


In [45]:
import numpy as np
numbers = np.array([4,9,16,25])

In [46]:
np.sqrt(numbers)

array([2., 3., 4., 5.])

In [47]:
np.sqrt(5)

np.float64(2.23606797749979)

In [48]:
import numpy as np

x = np.array([3,5,8])
y = np.array([4,12,15])

distances = np.sqrt(x**2 + y**2)
print(distances)


[ 5. 13. 17.]


In [50]:

x = np.array([3,5,8])
print(x**3)

[ 27 125 512]


In [51]:
np.power(x,3)

array([ 27, 125, 512])

In [53]:
a = 27,125,512
a = np.cbrt(a)
print(a)

[3. 5. 8.]


In [55]:
numbers = np.array([-10,5,10,0,5,10])
np.abs(numbers)

array([10,  5, 10,  0,  5, 10])

In [57]:
n = len(numbers)
for i in range(n):
  if numbers[i] <0:
    numbers[i]*=-1

print(numbers)

[10  5 10  0  5 10]


In [58]:
np.sqrt(np.square(numbers))

array([10.,  5., 10.,  0.,  5., 10.])

In [61]:
values = np.array([10.2345,20.6789,30.4567])

In [62]:
np.around(values)

array([10., 21., 30.])

In [63]:
np.around(values,2)

array([10.23, 20.68, 30.46])

In [64]:
values = np.array([2.1,2.9,5.5,7.99])
# round down
np.floor(values)

array([2., 2., 5., 7.])

In [65]:
values = np.array([2.1,2.9,5.5,7.99])
# round up
np.ceil(values)


array([3., 3., 6., 8.])

In [66]:
values = np.array([2.9,5.7,-3.8,-7.2])  #floor for postive numbers
np.trunc(values) # trunc for negative positive both

array([ 2.,  5., -3., -7.])

In [ ]:
# An e-commerce company stores order information.
# orders = np.array([
#     [1000, 2, 500],
#     [1001, 3, 750],
#     [1002, 1, 1200],
#     [1003, 4, 300],
#     [1004, 2, 900]
# ])

# Columns:

# Column 1 → Order ID
# Column 2 → Quantity
# Column 3 → Price per item

# Tasks

# Display the complete information of Order 1002.
# Display all quantities.
# Display all prices.
# Display the first 3 orders.
# Display the last 2 orders.
# Increase the price of the last 2 products by 10%.
# Increase the quantity of the first order by 1.
# Display the final dataset.
# Create a separate array containing only the quantity and price columns.
# Display the shape and size of the dataset

In [75]:
orders = np.array([
    [1000, 2, 500],
    [1001, 3, 750],
    [1002, 1, 1200],
    [1003, 4, 300],
    [1004, 2, 900]
])

In [76]:
# Display the complete information of Order 1002.
print(orders[2])

[1002    1 1200]


In [77]:
# Display all quantities.
print(orders[:,1])

[2 3 1 4 2]


In [78]:
# Display all prices.
print(orders[:,2])

[ 500  750 1200  300  900]


In [79]:
# Display the first 3 orders.
print(orders[:3])

[[1000    2  500]
 [1001    3  750]
 [1002    1 1200]]


In [80]:
# Display the last 2 orders.
print(orders[-2:])

[[1003    4  300]
 [1004    2  900]]


In [81]:
# Increase the price of the last 2 products by 10%.
orders[-2:,2]=orders[-2:,2]*1.10
print(orders)

[[1000    2  500]
 [1001    3  750]
 [1002    1 1200]
 [1003    4  330]
 [1004    2  990]]


In [82]:
# Increase the quantity of the first order by 1.
orders[0:1,1]+=1
print(orders)

[[1000    3  500]
 [1001    3  750]
 [1002    1 1200]
 [1003    4  330]
 [1004    2  990]]


In [83]:
# Display the final dataset.
print(orders)


[[1000    3  500]
 [1001    3  750]
 [1002    1 1200]
 [1003    4  330]
 [1004    2  990]]


In [84]:
# Create a separate array containing only the quantity and price columns.
print(orders[:,1:3])

[[   3  500]
 [   3  750]
 [   1 1200]
 [   4  330]
 [   2  990]]


In [85]:
# Display the shape and size of the dataset.
print(orders.shape)
print(orders.size)

(5, 3)
15
