In [1]:
# A simple grayscale image can be represented as a 2D NumPy array where each number represents pixel intensity.

# image = np.array([
#     [10, 20, 30, 40, 50],
#     [20, 30, 40, 50, 60],
#     [30, 40, 50, 60, 70],
#     [40, 50, 60, 70, 80],
#     [50, 60, 70, 80, 90]
# ])

# Tasks
# Find the dimensions of the image.
# Find its shape.
# Find the total number of pixels.
# Display the center pixel.
# Extract the top-left 3 x 3 region.
# Extract the bottom-right 2 x 2 region.
# Increase the intensity of the center 3 x 3 region by 20.
# Display the modified image.

In [2]:
import numpy as np

image = np.array([
    [10, 20, 30, 40, 50],
    [20, 30, 40, 50, 60],
    [30, 40, 50, 60, 70],
    [40, 50, 60, 70, 80],
    [50, 60, 70, 80, 90]
])

In [3]:
# Find the dimensions of the image.
image.ndim


2

In [4]:
# Find its shape.
image.shape

(5, 5)

In [5]:
# Find the total number of pixels.
image.size

25

In [6]:
image

array([[10, 20, 30, 40, 50],
       [20, 30, 40, 50, 60],
       [30, 40, 50, 60, 70],
       [40, 50, 60, 70, 80],
       [50, 60, 70, 80, 90]])

In [7]:
# Display the center pixel.
print(image[2,2])

50


In [8]:
# Extract the top-left 3 x 3 region.
print(image[0:3,0:3])

[[10 20 30]
 [20 30 40]
 [30 40 50]]


In [9]:
# Extract the bottom-right 2 x 2 region.
print(image[-2:,-2:])

[[70 80]
 [80 90]]


In [10]:
image

array([[10, 20, 30, 40, 50],
       [20, 30, 40, 50, 60],
       [30, 40, 50, 60, 70],
       [40, 50, 60, 70, 80],
       [50, 60, 70, 80, 90]])

In [11]:
# Increase the intensity of the center 3 x 3 region by 20.
image[1:4,1:4]+=20
print(image)

[[10 20 30 40 50]
 [20 50 60 70 60]
 [30 60 70 80 70]
 [40 70 80 90 80]
 [50 60 70 80 90]]


In [12]:
image[1:4,1:4]

array([[50, 60, 70],
       [60, 70, 80],
       [70, 80, 90]])

In [13]:
# Display the modified image.
print(image)

[[10 20 30 40 50]
 [20 50 60 70 60]
 [30 60 70 80 70]
 [40 70 80 90 80]
 [50 60 70 80 90]]


In [14]:
# A company stores quarterly revenue and expenses:

# financials = np.array([
#     [120, 80],
#     [150, 90],
#     [180, 110],
#     [200, 130]
# ])

# Rows = Q1, Q2, Q3, Q4
# Columns = Revenue, Expense

# Tasks
# Display Q2's complete financial data.
# Display all quarterly revenues.
# Display all quarterly expenses.
# Extract Q2 and Q3 data.
# Increase Q4 revenue by 15%.
# Reduce Q1 expense by 10%.
# Display the final financial matrix.

In [15]:
financials = np.array([
    [120, 80],
    [150, 90],
    [180, 110],
    [200, 130]
])

In [16]:
# Display Q2's complete financial data.
print(financials[1])

[150  90]


In [17]:
# Display all quarterly revenues.
print(financials[:,0])

[120 150 180 200]


In [18]:
# Display all quarterly expenses.
print(financials[:,1])

[ 80  90 110 130]


In [19]:
# Extract Q2 and Q3 data.
print(financials[1:3])

[[150  90]
 [180 110]]


In [20]:
# Increase Q4 revenue by 15%.
financials[3:,0]=financials[3:,0]*1.15
print(financials)

[[120  80]
 [150  90]
 [180 110]
 [229 130]]


In [21]:
# Reduce Q1 expense by 10%.
financials[0:,1]=financials[0:,1]*0.9
print(financials)

[[120  72]
 [150  81]
 [180  99]
 [229 117]]


In [22]:
# Display the final financial matrix.
print(financials)

[[120  72]
 [150  81]
 [180  99]
 [229 117]]


In [23]:
# A classroom has 6 rows and 5 seats per row.

# Initially, all seats are empty.

# 0 = Empty
# 1 = Occupied

# Tasks
# Create a 6 x 5 array filled with zeros.
# Mark the first seat of the first row as occupied.
# Mark all seats in the 3rd row as occupied.
# Mark the last two seats of the last row as occupied.
# Display the first 3 rows.
# Display the last 2 columns.
# Display the complete seating matrix.

In [24]:
# Create a 6 x 5 array filled with zeros.
seats =np.zeros((6,5),dtype=int)
print(seats)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [25]:
# Mark the first seat of the first row as occupied.
seats[0,0]=1
print(seats)

[[1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [26]:
# Mark all seats in the 3rd row as occupied.
seats[2]= 1
print(seats)

[[1 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [27]:
# Mark the last two seats of the last row as occupied.
seats[-1,-2:]=1
print(seats)

[[1 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 1]]


In [28]:
# Display the first 3 rows.
print(seats[:3])

[[1 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]]


In [29]:
# Display the last 2 columns.
print(seats[:,-2:])

[[0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]]


In [30]:
# Display the complete seating matrix.
print(seats)

[[1 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 1]]


In [31]:
sales = np.array([100,200,300,400,500])
print(np.sum(sales))
print(np.average(sales))
print(np.mean(sales))

1500
300.0
300.0


In [32]:
# Find the minimum salary
print(np.min(sales))

100


In [33]:
# Find the max salary
print(np.max(sales))

500


In [34]:
sales = np.array([-100,-200,-300,-400,-500])
print(np.min(sales))
print(np.max(sales))

-500
-100


In [35]:
sales = np.array([50,30,10,190,100])    #middle element of the sorted function
print(np.median(sales))

50.0


In [36]:
# A teacher has recorded marks of 10 students:

# marks = np.array([72, 85, 91, 64, 78, 88, 95, 70, 82, 76])

# Find:

# Total marks
# Average marks
# Highest marks
# Lowest marks
# Difference between highest and lowest marks
# Index of the student with the highest marks

In [37]:
marks = np.array([72, 85, 91, 64, 78, 88, 95, 70, 82, 76])

In [38]:
# Total marks
print(np.sum(marks))

801


In [39]:
# Average marks
print(np.average(marks))

80.1


In [40]:
# Highest marks
print(np.max(marks))

95


In [41]:
# Lowest marks
print(np.min(marks))

64


In [42]:
# Difference between highest and lowest marks.
print(np.max(marks)-np.min(marks))

31


In [43]:
# Index of the student with the highest marks.
print(np.argmax(marks))


6


In [44]:
# A company's daily sales for 7 days are:

# sales = np.array([45000, 47000, 49000, 52000, 50000, 48000, 250000])

# Calculate the mean and median.

# Then determine which measure better represents a typical sales day when considering the unusually large sale.

# Also calculate the standard deviation.

In [45]:
sales = np.array([45000, 47000, 49000, 52000, 50000, 48000, 250000])

In [46]:
# Calculate the mean and median.
print(np.mean(sales))
print(np.median(sales))

77285.71428571429
49000.0


In [47]:
# Also calculate the standard deviation.
print("Standard deviation:", np.std(sales))

Standard deviation: 70540.18973143565
