In [1]:
import numpy as np
marks = np.array([70,80,65,90,75])

print(np.sum(marks))
print(np.mean(marks))
print(np.min(marks))
print(np.max(marks))

380
76.0
65
90


In [2]:
80>70

True

In [3]:
(80 < 90) and (20 > 30)

False

In [4]:
(80 < 90) or (20 > 30)

True

In [5]:
80 == 80

True

In [6]:
80 != 80

False

In [7]:
80 != 90

True

In [8]:
marks = np.array([70,80,65,90,75])
marks > 75

array([False,  True, False,  True, False])

In [11]:
# Write a code to filter in only the marks > 75.
marks = np.array([45,76,89,90,56,78,89])
marks[marks > 75]

array([76, 89, 90, 78, 89])

In [12]:
temperature = np.array([
     24,28,31,35,29,22,37,30
])
# temp atleast 32
temperature[temperature >= 32]

array([35, 37])

In [17]:
prices = np.array([
    499,799,1299,2499,3999,599
])
# prices between 600 and 1000
prices[(prices <= 1000) & (prices >= 600)]

array([799])

In [19]:
# Prices less than 600 or greater than 1000
prices[(prices<600) | (prices>1000)]

array([ 499, 1299, 2499, 3999,  599])

In [21]:
# Show prices not greater than 900
prices[prices <= 900]

array([499, 799, 599])

In [23]:
prices[~(prices>900)]

array([499, 799, 599])

In [24]:
marks = np.array([
    [72,85,90],
    [55,60,65],
    [88,92,95],
    [45,50,48]
])

In [25]:
# filter marks > 70
marks[marks > 70]

array([72, 85, 90, 88, 92, 95])

In [26]:
sales = np.array([
    [100,200,300],
    [400,500,600],
    [150,250,350]
])

In [29]:
# Find the values greater than 200 only in the first row:
sales[0] [sales[0]>200]

array([300])

In [33]:
product = np.array([
    [101,500],
    [102,1200],
    [103,800],
    [104,1500]
])

In [35]:
# We want products whose price is greater than 1,000
product[:,1] [product[:,1] > 1000]

array([1200, 1500])

In [36]:
prices = product[:,1]
prices[prices > 1000]

array([1200, 1500])

In [ ]:
# An electricity board records the monthly electricity consumption of
#  a household for one year:

# consumption = np.array([
#     180, 220, 195, 250,
#     280, 310, 295, 270,
#     240, 210, 190, 230
# ])

# Perform the following:

# 1. Find the total annual consumption.
# 2. Calculate average monthly consumption.
# 3. Find the highest and lowest consumption.
# 4. Find the month index with the highest consumption.
# 5. Extract the first 6 months using slicing.
# 6. Extract alternate months.
# 7. Find all months where consumption was greater than the annual average.
# 8. Calculate the percentage increase required if next year's consumption is
#  expected to be 8% higher.

In [53]:
consumption = np.array([
     180, 220, 195, 250,
     280, 310, 295, 270,
     240, 210, 190, 230
 ])

In [38]:
# 1. Find the total annual consumption.
print(np.sum(consumption))

2870


In [40]:
# 2. Calculate average monthly consumption.
print(np.average(consumption))

239.16666666666666


In [41]:
# 3. Find the highest and lowest consumption.
print(np.max(consumption))
print(np.min(consumption))

310
180


In [42]:
# 4. Find the month index with the highest consumption.
print(np.argmax(consumption))

5


In [43]:
# 5. Extract the first 6 months using slicing.
print(consumption[0:6])

[180 220 195 250 280 310]


In [46]:
# 6. Extract alternate months.
print(consumption[0:13:2])

[180 195 280 295 240 190]


In [54]:
# 7. Find all months where consumption was greater than the annual average.
consumption[consumption > np.average(consumption)]

array([250, 280, 310, 295, 270, 240])

In [55]:
# 8. Calculate the percentage increase required if next year's consumption is expected to be 8% higher.
consumption = consumption*1.08
print(consumption)

[194.4 237.6 210.6 270.  302.4 334.8 318.6 291.6 259.2 226.8 205.2 248.4]


In [ ]:
# The following array contains marks of 5 students in 4 subjects:

# marks = np.array([
#     [72, 85, 90, 78],
#     [65, 70, 75, 80],
#     [88, 92, 95, 90],
#     [55, 60, 58, 65],
#     [78, 82, 85, 88]
# ])

# Assume each row represents a student and each column represents a subject.

# Find:

# 1. Shape and size of the array.
# 2. Marks obtained by the third student.
# 3. Marks obtained in the second subject by all students.
# 4. Average marks of every student.
# 5. Average marks of every subject.
# 6. Students whose average is above 75.
# 7. Highest mark obtained in each subject.
# 8. The complete row of the student with the highest average.

In [56]:
marks = np.array([
    [72, 85, 90, 78],
    [65, 70, 75, 80],
    [88, 92, 95, 90],
    [55, 60, 58, 65],
    [78, 82, 85, 88]
])

In [57]:
# 1. Shape and size of the array.
print(np.shape(marks))
print(np.size(marks))

(5, 4)
20


In [59]:
# 2. Marks obtained by the third student.
print(marks[2])

[88 92 95 90]


In [60]:
# 3. Marks obtained in the second subject by all students.
print(marks[:,1])

[85 70 92 60 82]


In [62]:
# 4. Average marks of every student.
print(np.average(marks, axis=1))

[81.25 72.5  91.25 59.5  83.25]


In [63]:
# 5. Average marks of every subject.
print(np.average(marks, axis=0))

[71.6 77.8 80.6 80.2]


In [67]:
# 6. Students whose average is above 75.
marks[75<np.average(marks, axis=1)]

array([[72, 85, 90, 78],
       [88, 92, 95, 90],
       [78, 82, 85, 88]])

In [72]:
# 7. Highest mark obtained in each subject.
print(np.max(marks, axis=0))

[88 92 95 90]


In [70]:
# 8. The complete row of the student with the highest average.
print(np.argmax(np.average(marks, axis= 1)))

2


In [73]:
marks[2]

array([88, 92, 95, 90])

In [ ]:
# An online store has the following product prices:

# prices = np.array([
#     499.50, 799.90, 1299.75,
#     2499.50, 3999.90, 599.25,
#     899.80, 1599.40
# ])

# Perform:

# 1. Round prices to the nearest whole number.
# 2. Find products costing more than ₹1,000.
# 3. Calculate a 15% discount only on products costing more than ₹1,000.
# 4. Calculate the average discounted price of those products.
# 5. Find the most expensive original product.
# 6. Extract the last 4 products.
# 7. Calculate the square root of the final prices and round them to 2 decimal places.

In [81]:
prices = np.array([
    499.50, 799.90, 1299.75,
    2499.50, 3999.90, 599.25,
    899.80, 1599.40
])

In [82]:
# 1. Round prices to the nearest whole number.
np.round(prices)

array([ 500.,  800., 1300., 2500., 4000.,  599.,  900., 1599.])

In [83]:
# 2. Find products costing more than ₹1,000.
prices[prices>1000]

array([1299.75, 2499.5 , 3999.9 , 1599.4 ])

In [84]:
# 3. Calculate a 15% discount only on products costing more than ₹1,000.
prices = prices[prices>1000]*0.85
print(prices)

[1104.7875 2124.575  3399.915  1359.49  ]


In [85]:
# 4. Calculate the average discounted price of those products.
print(np.average(prices))

1997.191875


In [87]:
# 5. Find the most expensive original product.
print(np.max(prices))

3399.915


In [90]:
np.argmax(prices)

np.int64(2)

In [89]:
# 6. Extract the last 4 products.
print(prices[-4:])

[1104.7875 2124.575  3399.915  1359.49  ]


In [92]:
# 7. Calculate the square root of the final prices and round them to 2 decimal places.
sqrt_prices = np.sqrt(prices)
final = np.round(sqrt_prices,2)
print(final)

[33.24 46.09 58.31 36.87]
