In [1]:
import numpy as np
marks = np.array([45,72,88,31,65,90])

In [2]:
marks[marks>80]

array([88, 90])

In [3]:
print(marks[marks>30])

[45 72 88 31 65 90]


In [4]:
# np.where(condition, value_if_true, value_if_false)

In [5]:
marks = np.array([45,72,88,31,65,90])
# marks > 70--> "Good", else "Average"
result = np.where(marks >70, "Good", "Average")
print(result)

['Average' 'Good' 'Good' 'Average' 'Average' 'Good']


In [6]:
marks = np.array([45,72,88,31,65,90])
# Suppose students scoring below 50 get 5 grace marks.
new_marks = np.where(marks < 50, marks+5, marks )
print(new_marks)

[50 72 88 36 65 90]


In [7]:
# Suppose products costing more than ₹1,000 receive a 10% discount.
prices = np.array([500, 1200, 800, 2500, 1500])
new_prices = np.where(prices>1000, prices*0.90, prices )
print(new_prices)

[ 500. 1080.  800. 2250. 1350.]


In [8]:
salary = np.array([25000, 45000, 75000, 32000, 90000])
# Salary >= 50000 → High
# Salary < 50000 → Standard
n_salary = np.where(salary >= 50000, "High","Standard" )
print(n_salary)

['Standard' 'Standard' 'High' 'Standard' 'High']


In [9]:
marks = np.array([45,72,88,31,65,90])
# 90 or above → Excellent
# 50–89 → Pass
# Below 50 → Fail
result_marks = np.where(marks>=90,"Excellent",np.where(marks>50, "Pass", "Fail"))
print(result_marks)

['Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Excellent']


In [10]:
sales = np.array([950000, 650000, 300000, 800000, 450000])
# Categories:
# >= 800000 → "Top Performer"
# else if >= 500000 → "Good Performer"
# otherwise → "Needs Improvement"

In [11]:
rate_sales = np.where(sales>= 800000,"Top Performer",np.where(sales >= 500000, "Good performer", "Needs Improvement"))
print(rate_sales)

['Top Performer' 'Good performer' 'Needs Improvement' 'Top Performer'
 'Needs Improvement']


In [12]:
# Suppose a loan applicant must satisfy both:
# salary >= ₹50,000
# credit score >= 700
# then approve, else reject
# salary = np.array([60000, 40000, 75000, 55000, 30000])
# credit_score = np.array([720, 750, 680, 710, 800])

In [13]:
salary = np.array([60000, 40000, 75000, 55000, 30000])
credit_score = np.array([720, 750, 680, 710, 800])

In [14]:
approve = (salary >= 50000) & (credit_score >= 700)
print(np.where(approve, "Approve","Reject"))

['Approve' 'Reject' 'Reject' 'Approve' 'Reject']


In [15]:
# Suppose a customer receives free shipping if:
# order value >= ₹1,000
# OR
# customer is a premium customer.
# order_value = np.array([500, 1200, 700, 800, 1500])
# premium = np.array([False, False, True, False, True])

In [16]:
order_value = np.array([500, 1200, 700, 800, 1500])
premium = np.array([False, False, True, False, True])
free_shipping = (order_value >= 1000) | (premium == True)
print(np.where(free_shipping,"Free","Paid"))

['Paid' 'Free' 'Free' 'Paid' 'Free']


In [17]:
students = np.array([
[101, 78, 85, 92],
[102, 45, 55, 60],
[103, 91, 88, 95],
[104, 62, 70, 68],
[105, 35, 42, 50]
])
# Student_ID | Python | SQL | ML
# calculate avg marks of each student

In [18]:
students = np.array([
[101, 78, 85, 92],
[102, 45, 55, 60],
[103, 91, 88, 95],
[104, 62, 70, 68],
[105, 35, 42, 50]
])

avg_marks=(np.average(students[:,1:],axis=1))
print(avg_marks)

[85.         53.33333333 91.33333333 66.66666667 42.33333333]


In [19]:
# Let's classify students as:
# Average >= 85 → Excellent
# Average >= 60 → Good
# Average >= 50 → Pass
# Otherwise → Fail
ans = np.where(avg_marks >= 85, "Excellent",np.where(avg_marks>=60, "Good",np.where(avg_marks>=50,"Average","Fail")))
print(ans)

['Excellent' 'Average' 'Excellent' 'Good' 'Fail']


In [20]:
# A business records revenue for 12 months:
# revenue = np.array([
# 120000, 135000, 128000, 145000,
# 150000, 138000, 160000, 172000,
# 155000, 148000, 180000, 195000
# ])
# Find:
# Average monthly revenue
# Highest revenue
# Lowest revenue
# Month index with highest revenue
# Month index with lowest revenue
# Total annual revenue
# Difference between highest and lowest revenue

In [21]:
revenue = np.array([
120000, 135000, 128000, 145000,
150000, 138000, 160000, 172000,
155000, 148000, 180000, 195000
])

In [22]:
# Average monthly revenue
print(np.average(revenue))

152166.66666666666


In [23]:
# Highest revenue
print(np.max(revenue))

195000


In [24]:
# Lowest revenue
print(np.min(revenue))

120000


In [25]:
# Month index with highest revenue
print(np.argmax(revenue))

11


In [26]:
# Month index with lowest revenue
print(np.argmin(revenue))

0


In [27]:
# Total annual revenue
print(np.sum(revenue))

1826000


In [51]:
# show the quaterly total revenue.
qtr = []
qtr.append(revenue[:3])
qtr.append(revenue[3:6])
qtr.append(revenue[6:9])
qtr.append(revenue[9:12])

In [55]:
qtr

[array([120000, 135000, 128000]),
 array([145000, 150000, 138000]),
 array([160000, 172000, 155000]),
 array([148000, 180000, 195000])]

In [28]:
# Difference between highest and lowest revenue
print(np.max(revenue)-np.min(revenue))

75000


In [29]:
# The following array contains sales made by 4 salespeople across 3 months.
# sales = np.array([
# [120, 150, 180],
# [200, 170, 160],
# [100, 140, 130],
# [180, 190, 210]
# ])
# Rows represent salespeople and columns represent months.
# Find:
# Total sales by each salesperson
# Average sales by each salesperson
# Total sales for each month
# Average sales for each month
# Highest sales achieved by each salesperson

In [30]:
sales = np.array([
[120, 150, 180],
[200, 170, 160],
[100, 140, 130],
[180, 190, 210]
])

In [31]:
# Total sales by each salesperson
print(np.sum(sales,axis=1))

[450 530 370 580]


In [32]:
# Average sales by each salesperson
print(np.average(sales , axis=1))

[150.         176.66666667 123.33333333 193.33333333]


In [33]:
# Total sales for each month
print(np.sum(sales, axis=0))

[600 650 680]


In [34]:
print(np.average(sales, axis=0))

[150.  162.5 170. ]


In [35]:
# Highest sales achieved by each salesperson
print(np.max(sales, axis=1))

[180 200 140 210]


In [36]:
# Consider:
# employees = np.array([
# [101, 35000, 2],
# [102, 48000, 4],
# [103, 62000, 6],
# [104, 40000, 3],
# [105, 75000, 8],
# [106, 55000, 5]
# ])
# Columns represent:
# Employee ID | Salary | Experience
# Find:
# Employees earning more than ₹50,000.
# Employees with more than 4 years of experience.
# Employees earning more than ₹50,000 AND having more than 4 years of experience.
# Average salary of employees satisfying condition 3.
# Employee with the highest salary.
# Employees earning below the median salary.

In [37]:
employees = np.array([
[101, 35000, 2],
[102, 48000, 4],
[103, 62000, 6],
[104, 40000, 3],
[105, 75000, 8],
[106, 55000, 5]
])

In [38]:
# Employees earning more than ₹50,000.
print(employees[employees[:,1]>50000])

[[  103 62000     6]
 [  105 75000     8]
 [  106 55000     5]]


In [39]:
# Employees with more than 4 years of experience.
print(employees[employees[:,2]>4])

[[  103 62000     6]
 [  105 75000     8]
 [  106 55000     5]]


In [40]:
# Employees earning more than ₹50,000 AND having more than 4 years of experience.
print(employees[employees[:,1]>50000]& employees[employees[:,2]>4])

[[  103 62000     6]
 [  105 75000     8]
 [  106 55000     5]]


In [46]:
# Average salary of employees satisfying condition 3.
cond3 = employees[employees[:,1]>50000]& employees[employees[:,2]>4]
print(np.average(cond3))

21370.333333333332


In [47]:
# Employee with the highest salary.
highest = employees[employees[:,1].argmax()]
print(highest)

[  105 75000     8]


In [48]:
# Employees earning below the median salary.
median_salary = np.median(employees[:,1])
below_median = employees[employees[:,1] < median_salary]
print("Median Salary:", median_salary)
print(below_median)

Median Salary: 51500.0
[[  101 35000     2]
 [  102 48000     4]
 [  104 40000     3]]
