In [1]:
# Give students this towards the end.
# employees = np.array([
# [101, 45000, 120000],
# [102, 60000, 180000],
# [103, 35000, 90000],
# [104, 75000, 250000],
# [105, 50000, 160000]
# ])
# Columns:
# Employee_ID | Salary | Sales
# # Employees with sales >= ₹150,000 receive 5% commission otherwise 2% commision.
# # 2. Sales > 200000, excellent, 150000 --> good, else improvement.

In [2]:
import numpy as np
employees = np.array([
[101, 45000, 120000],
[102, 60000, 180000],
[103, 35000, 90000],
[104, 75000, 250000],
[105, 50000, 160000]
])

In [3]:
# Employees with sales >= ₹150,000 receive 5% commission otherwise 2% commision.
sales = employees[:,2]
print(sales)

[120000 180000  90000 250000 160000]


In [4]:
import numpy as np
employees = np.array([
[101, 45000, 120000],
[102, 60000, 180000],
[103, 35000, 90000],
[104, 75000, 250000],
[105, 50000, 160000]
])
sales = employees[:,2]
# 2. Sales > 200000, excellent, 150000 --> good, else improvement.
category = np.where(sales > 200000, "Excellent", np.where(sales>150000,"Good","Improvement"))
print(category)

['Improvement' 'Good' 'Improvement' 'Excellent' 'Good']


In [5]:
# Employees with sales >= ₹150,000 receive 5% commission otherwise 2% commision.
comission = np.where(sales>150000,sales*0.05,sales*0.02)
print(comission)

[ 2400.  9000.  1800. 12500.  8000.]


In [6]:
import numpy as np
sales = np.array([
120, 150, 180, 200,
220, 250, 270, 300,
320, 350, 380, 400
])
print(sales)

[120 150 180 200 220 250 270 300 320 350 380 400]


In [7]:
# 4 quarters --> 3 months each

In [8]:
sales.ndim

1

In [9]:
sales.shape

(12,)

In [10]:
sales.size

12

In [11]:
qtr_sales = sales.reshape(4,3)
print(qtr_sales)

[[120 150 180]
 [200 220 250]
 [270 300 320]
 [350 380 400]]


In [12]:
qtr_sales.shape

(4, 3)

In [13]:
qtr_sales.ndim

2

In [14]:
numbers = np.array([1,2,3,4,5,6])
a =numbers.reshape(2,3)
print(a)

[[1 2 3]
 [4 5 6]]


In [15]:
marks = np.array([
72, 81, 65, 90, 77,
88, 69, 91, 73, 84,
60, 75, 82, 79, 95,
68, 71, 86, 89, 93
])
# 4*5
# sum of each row

In [16]:
# 4*5
n_m = marks.reshape(4,5)
print(n_m)

[[72 81 65 90 77]
 [88 69 91 73 84]
 [60 75 82 79 95]
 [68 71 86 89 93]]


In [17]:
# sum of each row
np.sum(n_m,axis=1)

array([385, 405, 391, 407])

In [18]:
n_m = marks.reshape(5,-1)
n_m

array([[72, 81, 65, 90],
       [77, 88, 69, 91],
       [73, 84, 60, 75],
       [82, 79, 95, 68],
       [71, 86, 89, 93]])

In [19]:
n_m = marks.reshape(-1,2)
n_m

array([[72, 81],
       [65, 90],
       [77, 88],
       [69, 91],
       [73, 84],
       [60, 75],
       [82, 79],
       [95, 68],
       [71, 86],
       [89, 93]])

In [20]:
b = n_m.reshape(-1,4)
b


array([[72, 81, 65, 90],
       [77, 88, 69, 91],
       [73, 84, 60, 75],
       [82, 79, 95, 68],
       [71, 86, 89, 93]])

In [21]:
matrix = np.array([
[10, 20, 30],
[40, 50, 60],
[70, 80, 90]
])

In [22]:
matrix.shape

(3, 3)

In [23]:
a = matrix.flatten()
print(a)

[10 20 30 40 50 60 70 80 90]


In [24]:
print(matrix.shape)

(3, 3)


In [25]:
a.shape

(9,)

In [26]:
sales = np.array([
[100, 120, 150],
[90, 110, 130],
[200, 220, 250]
])
# want the average sales for all 9 months
np.mean(sales)

np.float64(152.22222222222223)

In [27]:
np.mean(sales,axis = 1)

array([123.33333333, 110.        , 223.33333333])

In [28]:
np.mean(sales,axis=0)

array([130.        , 150.        , 176.66666667])

In [29]:
a =sales.flatten()
np.mean(a)

np.float64(152.22222222222223)

In [30]:
a = np.arange(30)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [31]:
b = a.reshape(2,5,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [32]:
b[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [33]:
b[0,1]

array([3, 4, 5])

In [34]:
b[1]

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [35]:
#  An e-commerce company records the quantity sold and selling price of 12 products.
quantity = np.array([2, 5, 3, 8, 4, 6, 10, 1, 7, 5, 9, 3])
price = np.array([
1200, 800, 1500, 450, 2200, 900,
700, 1800, 650, 1300, 500, 2500
])

In [36]:
# Calculate revenue for every product.
# Calculate the total revenue.
# Find the product index generating the highest revenue.
# Extract the revenue of the last five products.

In [37]:
# Calculate revenue for every product.
revenue = quantity*price
print(revenue)

[2400 4000 4500 3600 8800 5400 7000 1800 4550 6500 4500 7500]


In [38]:
# Calculate the total revenue.
print(np.sum(revenue))

60550


In [39]:
# Find the product index generating the highest revenue.
np.argmax(revenue)

np.int64(4)

In [40]:
# Extract the revenue of the last five products.
print(revenue[-5:])

[1800 4550 6500 4500 7500]


In [41]:
# Find products whose revenue is above the average revenue.
# Apply a 10% discount only to products whose price is greater than ₹1,000.
# Round the discounted prices to two decimal places.
# Calculate the total quantity sold.
# Find the median product price.
# Identify products whose price is above the median and whose quantity is at least 5.

In [42]:
# Find products whose revenue is above the average revenue.
revenue[revenue > np.mean(revenue)]

array([8800, 5400, 7000, 6500, 7500])

In [43]:
np.where(revenue > np.mean(revenue),"Yes","No")

array(['No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes',
       'No', 'Yes'], dtype='<U3')

In [44]:
# Apply a 10% discount only to products whose price is greater than ₹1,000.
discount_price = np.where(price>1000,price*0.9,price)
print(discount_price)

[1080.  800. 1350.  450. 1980.  900.  700. 1620.  650. 1170.  500. 2250.]


In [45]:
# Round the discounted prices to two decimal places.
discount_price = np.round(discount_price,2)
print(discount_price)

[1080.  800. 1350.  450. 1980.  900.  700. 1620.  650. 1170.  500. 2250.]


In [46]:
# Calculate the total quantity sold.
np.sum(quantity)

np.int64(63)

In [47]:
# Find the median product price.
median = np.median(price)
print(median)

1050.0


In [48]:
# Identify products whose price is above the median and whose quantity is at least 5.
prds =(price > median) & (quantity >= 5)
price[prds]

array([1300])

In [49]:
criteria = (price > median) & (quantity >= 5)
price[criteria]

array([1300])

In [50]:
# A college has performance scores for 24 assessments:
# scores = np.array([
# 72, 81, 65, 90,
# 77, 88, 69, 91,
# 73, 84, 60, 75,
# 82, 79, 95, 68,
# 71, 86, 89, 93,
# 66, 74, 80, 87
# ])
# Assume there are 6 students and 4 assessments per student.
# Verify the number of elements.
# Reshape the array into a 6 × 4 matrix.
# Calculate the average score for each student.
# Find the highest score achieved by each student.

In [51]:
scores = np.array([
72, 81, 65, 90,
77, 88, 69, 91,
73, 84, 60, 75,
82, 79, 95, 68,
71, 86, 89, 93,
66, 74, 80, 87
])

In [52]:
# Reshape the array into a 6 × 4 matrix.
a = scores.reshape(6,4)
print(a)

[[72 81 65 90]
 [77 88 69 91]
 [73 84 60 75]
 [82 79 95 68]
 [71 86 89 93]
 [66 74 80 87]]


In [53]:
print(np.average(a,axis=1))


[77.   81.25 73.   81.   84.75 76.75]


In [54]:
# Find the highest score achieved by each student.
print(np.max(a,axis=1))

[90 91 84 95 93 87]


In [56]:
# A college has performance scores for 24 assessments:
# scores = np.array([
# 72, 81, 65, 90,
# 77, 88, 69, 91,
# 73, 84, 60, 75,
# 82, 79, 95, 68,
# 71, 86, 89, 93,
# 66, 74, 80, 87
# ])
# Assume there are 6 students and 4 assessments per student
# Verify the number of elements.
# Reshape the array into a 6 × 4 matrix.
# Calculate the average score for each student.
# Find the highest score achieved by each student.

In [55]:
scores = np.array([
72, 81, 65, 90,
77, 88, 69, 91,
73, 84, 60, 75,
82, 79, 95, 68,
71, 86, 89, 93,
66, 74, 80, 87
])

In [57]:
# Verify the number of elements.
print(np.size(scores))

24


In [59]:
# Reshape the array into a 6 × 4 matrix.
a = scores.reshape(6,4)
print(a)

[[72 81 65 90]
 [77 88 69 91]
 [73 84 60 75]
 [82 79 95 68]
 [71 86 89 93]
 [66 74 80 87]]


In [61]:
print(np.average(a,axis=1))

[77.   81.25 73.   81.   84.75 76.75]


In [62]:
# Find the highest score achieved by each student.
print(np.max(a,axis=1))

[90 91 84 95 93 87]


In [ ]:
# Find the student index having the highest overall average.

# Create performance labels:
# average >= 85 → "Excellent"
# average >= 70 → "Good"
# average >= 50 → "Pass"
# otherwise → "Fail"

# Extract students whose average is above the overall average

In [64]:
# Find the student index having the highest overall average.
np.argmax(np.average(a,axis=1))

np.int64(4)

In [67]:
# Create performance labels:
# average >= 85 → "Excellent"
# average >= 70 → "Good"
# average >= 50 → "Pass"
# otherwise → "Fail"
avg = np.average(a,axis=1)
np.where(avg >= 85, "Excellent",np.where(avg >=70,"Good",np.where(avg >= 50, "Pass" ,"Fail") ))

array(['Good', 'Good', 'Good', 'Good', 'Good', 'Good'], dtype='<U9')

In [70]:
avg_score = np.average(scores)
print(avg_score)

78.95833333333333


In [72]:
# Extract students whose average is above the overall average
np.where(avg > avg_score,"Yes","No" )

array(['No', 'Yes', 'No', 'Yes', 'Yes', 'No'], dtype='<U3')

In [ ]:
# Extract the last two assessments of every student.
# Flatten the complete matrix.
# Calculate the percentage of all assessment scores that are above 80

In [73]:
a

array([[72, 81, 65, 90],
       [77, 88, 69, 91],
       [73, 84, 60, 75],
       [82, 79, 95, 68],
       [71, 86, 89, 93],
       [66, 74, 80, 87]])

In [74]:
# Extract the last two assessments of every student.
print(a[:,-2:])

[[65 90]
 [69 91]
 [60 75]
 [95 68]
 [89 93]
 [80 87]]


In [76]:
# Flatten the complete matrix.
scores.flatten()

array([72, 81, 65, 90, 77, 88, 69, 91, 73, 84, 60, 75, 82, 79, 95, 68, 71,
       86, 89, 93, 66, 74, 80, 87])

In [77]:
# Calculate the percentage of all assessment scores that are above 80
grt_80 = scores[scores > 80]
print(grt_80)

[81 90 88 91 84 82 95 86 89 93 87]


In [78]:
a = len(grt_80)
n = len(scores)
perc = a*100/n
print(perc)

45.833333333333336


In [79]:
# A company's monthly sales for one year are:
sales = np.array([
120000, 135000, 128000, 150000,
160000, 172000, 165000, 180000,
195000, 210000, 205000, 225000
])

In [ ]:
# Calculate the average monthly sales.
# Find the median sales.
# Find the month with the highest sales.
# Calculate the standard deviation

In [80]:
# Calculate the average monthly sales.
np.average(sales)

np.float64(170416.66666666666)

In [81]:
# Find the median sales.
np.median(sales)

np.float64(168500.0)

In [84]:
# Find the month with the highest sales.
np.argmax(sales)

np.int64(11)

In [85]:
# Calculate the standard deviation
np.std(sales)

np.float64(32392.021479919335)

In [ ]:
# Create a forecast for the next 6 months using np.linspace() between:
# the minimum observed sales
# and 20% above the maximum observed sales.
# Round the forecast values to the nearest rupee.
# Combine the original sales and forecast into one 18-element array.
# Reshape the combined array into 3 × 6.
# Calculate the average sales for each row.
# Identify values that are greater than the overall median.

In [86]:
mn_s = np.min(sales)
mx_s = np.max(sales)
mx_s20 = mx_s*1.20

In [88]:
forecast = np.linspace(mn_s,mx_s20,6)
forecast

array([120000., 150000., 180000., 210000., 240000., 270000.])

In [89]:
# Round the forecast values to the nearest rupee.
r_s = np.round(forecast,2)

In [90]:
r_s

array([120000., 150000., 180000., 210000., 240000., 270000.])

In [91]:
# Combine the original sales and forecast into one 18-element array.
n_s = np.append(sales,r_s)

In [92]:
n_s

array([120000., 135000., 128000., 150000., 160000., 172000., 165000.,
       180000., 195000., 210000., 205000., 225000., 120000., 150000.,
       180000., 210000., 240000., 270000.])

In [93]:
# Reshape the combined array into 3 × 6.
ans = n_s.reshape(3,6)
ans

array([[120000., 135000., 128000., 150000., 160000., 172000.],
       [165000., 180000., 195000., 210000., 205000., 225000.],
       [120000., 150000., 180000., 210000., 240000., 270000.]])

In [94]:
# Calculate the average sales for each row.
np.mean(ans,axis=1)

array([144166.66666667, 196666.66666667, 195000.        ])

In [95]:
# Identify values that are greater than the overall median.
np.where(n_s > np.median(n_s),"Yes","No")

array(['No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes',
       'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes'], dtype='<U3')