In [1]:
# import numpy as np

# loan_amount = np.array([
#     100000, 250000, 500000, 750000,
#     120000, 350000, 900000, 450000
# ])

# interest_rate = np.array([
#     8.5, 9.2, 8.8, 10.1,
#     7.9, 9.5, 10.5, 8.7
# ])

# Categorize loans:
# Rate >= 10 → High
# Rate >= 9 → Medium
# Otherwise → Low

# Round interest to 2 decimal places.

# Find median loan amount.

# Find loans above median amount AND interest above average interest.

# Calculate standard deviation of interest rates.

In [2]:
import numpy as np

loan_amount = np.array([
    100000, 250000, 500000, 750000,
    120000, 350000, 900000, 450000
])

interest_rate = np.array([
    8.5, 9.2, 8.8, 10.1,
    7.9, 9.5, 10.5, 8.7
])

In [3]:
# Categorize loans:
# Rate >= 10 → High
# Rate >= 9 → Medium
# Otherwise → Low
categories = np.where(interest_rate >= 10,"High",np.where(interest_rate>=9,"Medium","Low"))
print(categories)

['Low' 'Medium' 'Low' 'High' 'Low' 'Medium' 'High' 'Low']


In [4]:
# Round interest to 2 decimal places.
intrest = loan_amount*interest_rate/100
round = np.round(intrest,2)
print(round)

[ 8500. 23000. 44000. 75750.  9480. 33250. 94500. 39150.]


In [5]:
# Find median loan amount.
median = np.median(loan_amount)
print(median)

400000.0


In [7]:
# Find loans above median amount AND interest above average interest.
avg_intrest = np.average(interest_rate)
criteria = (loan_amount > median) & (interest_rate >avg_intrest)
loan_amount[criteria]

array([750000, 900000])

In [9]:
# Calculate standard deviation of intrest rates.
std_dev = np.std(interest_rate)
print(std_dev)

0.8031189202104504


In [ ]:
# The coordinates of eight delivery locations are:
# points = np.array([
# [3, 4],
# [5, 12],
# [8, 15],
# [7, 24],
# [9, 40],
# [12, 35],
# [15, 20],
# [6, 8]
# ])

# Each row contains:

# [x, y]

# Calculate distance from the origin using:

# distance = √(x² + y²)

# Extract x and y coordinates.

# Calculate distance for every location.

# Round distances to 2 decimals.

# Find nearest and farthest location.

# Find average distance.

# Find locations above average distance.

# Categorize:
# if >= 30 → Long
# elif >= 15 → Medium
# otherwise --> short

# Find percentage of Long-Distance delivery.

# Flatten the coordinate array.

# Find the size of flatten array.

In [10]:
points = np.array([
[3, 4],
[5, 12],
[8, 15],
[7, 24],
[9, 40],
[12, 35],
[15, 20],
[6, 8]
])

In [ ]:
# Calculate distance from the origin using:
# distance = √(x² + y²)

In [11]:
# Extract x and y coordinates.
x = points[:,0]
y = points[:,1]
print("x = ",x)
print("y = ",y)

x =  [ 3  5  8  7  9 12 15  6]
y =  [ 4 12 15 24 40 35 20  8]


In [13]:
# Calculate distance for every location.
distances = np.sqrt(np.square(x)+np.square(y))
distances

array([ 5., 13., 17., 25., 41., 37., 25., 10.])

In [15]:
# Round distances to 2 decimals.
round_dist = np.round(distances)
print(round_dist)

[ 5. 13. 17. 25. 41. 37. 25. 10.]


In [19]:
# Find nearest and farthest location.
nearest_location = np.min(distances)
print(nearest_location)


5.0


In [20]:
# Find average distance.
avg_distance = np.average(distances)
print(avg_distance)

21.625


In [22]:
# Find locations above average distance.
points[distances > avg_distance]

array([[ 7, 24],
       [ 9, 40],
       [12, 35],
       [15, 20]])

In [25]:
# Categorize:
# if >= 30 → Long
# elif >= 15 → Medium
# otherwise --> short
categorize = np.where(distances >= 30, "Long",np.where(distances >= 15,"Medium","short"))
print(categorize)

['short' 'short' 'Medium' 'Medium' 'Long' 'Long' 'Medium' 'short']


In [28]:
# Find percentage of Long-Distance delivery.
long_dist = categorize[categorize == "Long"]
n = len(distances)
m = len(long_dist)
perc = (m*100)/n
print(perc)

25.0


In [30]:
# Flatten the coordinate array.
flatten_array = points.flatten()
print(flatten_array)

[ 3  4  5 12  8 15  7 24  9 40 12 35 15 20  6  8]


In [31]:
# Find the size of flatten array.
n = np.size(flatten_array)
print(" Size of Flatten array = ",n)

 Size of Flatten array =  16


In [ ]:
# patients = np.array([
#     [101, 120, 85, 98],
#     [102, 135, 92, 96],
#     [103, 110, 78, 99],
#     [104, 150, 88, 94],
#     [105, 125, 95, 97],
#     [106, 160, 82, 93],
#     [107, 115, 90, 98],
#     [108, 145, 87, 95],
#     [109, 130, 91, 96],
#     [110, 155, 80, 92]
# ])

# # Patient_ID, Heart_Rate, Oxygen_Level, Recovery_Score

# Calculate average heart rate.
# Calculate median oxygen level.
# Find patients with heart rate above average AND oxygen below 90.

In [32]:
patients = np.array([
    [101, 120, 85, 98],
    [102, 135, 92, 96],
    [103, 110, 78, 99],
    [104, 150, 88, 94],
    [105, 125, 95, 97],
    [106, 160, 82, 93],
    [107, 115, 90, 98],
    [108, 145, 87, 95],
    [109, 130, 91, 96],
    [110, 155, 80, 92]
])

In [33]:
# Calculate average heart rate.
avg_heart_rate = np.average(patients[:,1])
print(avg_heart_rate)

134.5


In [34]:
# Calculate median oxygen level.
median_oxy_lvl = np.median(patients[:,2])
print(median_oxy_lvl)

87.5


In [37]:
# Find patients with heart rate above average AND oxygen below 90.
criterias = (patients[:,1]>avg_heart_rate) & (patients[:,2] < 90)
print(criterias)
patients[criterias]

[False False False  True False  True False  True False  True]


array([[104, 150,  88,  94],
       [106, 160,  82,  93],
       [108, 145,  87,  95],
       [110, 155,  80,  92]])

In [ ]:
# Categorize recovery:
# >= 97 → Excellent
# >= 95 → Stable
# Otherwise → Monitor

# Count each category.

# Find patient with highest heart rate.

# Calculate standard deviation of oxygen levels.

# Find oxygen levels more than 1 standard deviation below the mean.

# Extract the last 3 patients.

# Flatten the measurement data and calculate its mean.

In [40]:
# Categorize recovery:
# >= 97 → Excellent
# >= 95 → Stable
# Otherwise → Monitor
recovery = patients[:,-1]
Categorize_recovery = np.where(recovery >= 97, "Excellent", np.where(recovery >= 95,"Suitable","Monitor"))
print(Categorize_recovery)

['Excellent' 'Suitable' 'Excellent' 'Monitor' 'Excellent' 'Monitor'
 'Excellent' 'Suitable' 'Suitable' 'Monitor']


In [42]:
# Count each category.
count_excellent = len(Categorize_recovery[Categorize_recovery == "Excellent"])
count_suitable = len(Categorize_recovery[Categorize_recovery == "Suitable"])
count_monitor = len(Categorize_recovery[Categorize_recovery == "Monitor"])
print(count_excellent)
print(count_suitable)
print(count_monitor)

4
3
3


In [49]:
np.sum(Categorize_recovery == "Excellent")

np.int64(4)

In [50]:
np.sum(Categorize_recovery == "Suitable")

np.int64(3)

In [51]:
np.sum(Categorize_recovery == "Monitor")

np.int64(3)

In [52]:
# Find patient with highest heart rate.
highest_heart_rate = np.argmax(patients[:,1])
print(highest_heart_rate)

5


In [44]:
# Calculate standard deviation of oxygen levels.
std_oxy_lvl = np.std(patients[:,2])
print(std_oxy_lvl)

5.230678732248808


In [53]:
# Find oxygen levels more than 1 standard deviation below the mean.
std = np.std(patients[:,2])
print(std)

5.230678732248808


In [54]:
avg_oxy = np.mean(patients[:,2])
print(avg_oxy)

86.8


In [55]:
patients[:,2][patients[:,2]>(patients[:,2]-std)]

array([85, 92, 78, 88, 95, 82, 90, 87, 91, 80])

In [45]:
# Extract the last 3 patients.
print(patients[-3:])

[[108 145  87  95]
 [109 130  91  96]
 [110 155  80  92]]


In [46]:
# Flatten the measurement data and calculate its mean.
flatten = patients.flatten()
np.mean(flatten)

np.float64(105.65)

In [56]:
January = np.array([120,150,180])
February = np.array([140,160,200])
print(January)
print(February)

[120 150 180]
[140 160 200]


In [57]:
data = np.concatenate((January,February))
data

array([120, 150, 180, 140, 160, 200])

In [60]:
a = np.array([10,20])
b = np.array([30,40])
c = np.array([50,60,78,67])

result = np.concatenate((a,b,c))
print(result)

[10 20 30 40 50 60 78 67]


In [61]:
a = np.array([
    [1,2],
    [3,4]
])

In [62]:
b = np.array([
    [5,6],
    [7,8]
])

In [63]:
a

array([[1, 2],
       [3, 4]])

In [64]:
b

array([[5, 6],
       [7, 8]])

In [65]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
# axis = 1 ==> along the row/ vertically
# axis = 0 ==> along the columns/horizontally


In [66]:
a = np.array([
    [1,2],
    [3,4]
])

b = np.array([
    [5,6],
    [7,8]
])

In [68]:
res = np.concatenate((a,b),axis=0)
res

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [69]:
res = np.concatenate((a,b),axis=1)
res

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])