In [1]:
# # Inventory across four stores and five products:

# inventory = np.array([
#     [12, 45, 8, 32, 20],
#     [5, 60, 15, 25, 10],
#     [30, 18, 6, 40, 22],
#     [9, 55, 12, 28, 7]
# ])

# # Tasks:
# # Calculate total inventory per store.
# # Calculate total inventory per product.
# # Find the store with highest inventory.
# # Find the product with lowest total inventory.
# # Extract inventory values below 10.

In [2]:
import numpy as np
inventory = np.array([
    [12, 45, 8, 32, 20],
    [5, 60, 15, 25, 10],
    [30, 18, 6, 40, 22],
    [9, 55, 12, 28, 7]
])

In [3]:
# Calculate total inventory per store.
total_inventory_store = np.sum(inventory,axis=1)
print(total_inventory_store)

[117 115 116 111]


In [4]:
# Calculate total inventory per product.
total_inventory_product = np.sum(inventory,axis=0)
print(total_inventory_product)

[ 56 178  41 125  59]


In [5]:
# Find the store with highest inventory.
highest_inventory = np.argmax(total_inventory_store)
print(highest_inventory+1)

1


In [6]:
# Find the product with lowest total inventory.
lowest_inventory = np.argmin(total_inventory_product)
print(lowest_inventory+1)

3


In [7]:
# Extract inventory values below 10.
low_inventory = inventory[inventory < 10]
print(low_inventory)

[8 5 6 9 7]


In [8]:
# Count items that require replenishment.
# Create "Reorder" / "OK" labels.
# Increase inventory below 10 by 20%.
# Round the resulting inventory.
# Find median inventory.
# Extract the last two products.
# Flatten the inventory and calculate standard deviation.

In [9]:
# Count items that require replenishment.(<10)
n = len(low_inventory)
print(n)

5


In [10]:
m = np.sum(inventory < 10)
print(m)

5


In [11]:
# Create "Reorder" / "OK" labels.
label = np.where(inventory < 10, "Reorder","Ok")
print(label)

[['Ok' 'Ok' 'Reorder' 'Ok' 'Ok']
 ['Reorder' 'Ok' 'Ok' 'Ok' 'Ok']
 ['Ok' 'Ok' 'Reorder' 'Ok' 'Ok']
 ['Reorder' 'Ok' 'Ok' 'Ok' 'Reorder']]


In [12]:
# Increase inventory below 10 by 20%.
new_inv = np.where(inventory < 10, inventory*1.2, inventory )
print(new_inv)

[[12.  45.   9.6 32.  20. ]
 [ 6.  60.  15.  25.  10. ]
 [30.  18.   7.2 40.  22. ]
 [10.8 55.  12.  28.   8.4]]


In [13]:
# Round the resulting inventory.
round = np.round(new_inv)
print(round)

[[12. 45. 10. 32. 20.]
 [ 6. 60. 15. 25. 10.]
 [30. 18.  7. 40. 22.]
 [11. 55. 12. 28.  8.]]


In [14]:
# Find median inventory.
np.median(new_inv)


np.float64(19.0)

In [15]:
flat_inv = inventory.flatten()
flat_inv

array([12, 45,  8, 32, 20,  5, 60, 15, 25, 10, 30, 18,  6, 40, 22,  9, 55,
       12, 28,  7])

In [16]:
np.short(flat_inv)

array([12, 45,  8, 32, 20,  5, 60, 15, 25, 10, 30, 18,  6, 40, 22,  9, 55,
       12, 28,  7], dtype=int16)

In [17]:
# Extract the last two products.
print(inventory[:,-2:])

[[32 20]
 [25 10]
 [40 22]
 [28  7]]


In [18]:
# Flatten the inventory and calculate standard deviation.
std = np.std(flat_inv)
print(std)

16.00773250651072


In [19]:
a = np.array([10,20,30])
b = np.array([40,50,60])

result = np.concatenate((a,b))

print(result)

[10 20 30 40 50 60]


In [20]:
a = np.array([10,20])
b = np.array([30,40])
c = np.array([50,60])

result = np.concatenate((a,b,c))

print(result)

[10 20 30 40 50 60]


In [21]:
a = np.array([
    [1,2],
    [3,4]
])

b = np.array([
    [5,6],
    [7,8]
])

In [22]:
res = np.concatenate((a,b))
print(res)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [23]:
res = np.concatenate((a,b),axis=1)
print(res)

[[1 2 5 6]
 [3 4 7 8]]


In [24]:
res = np.concatenate((a,b),axis=0)
print(res)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [25]:
a = np.array([
    [1,2],
    [3,4],
    [6,7]
])

b = np.array([
    [5,6],
    [7,8]
])

In [26]:
a1 = np.concatenate((a,b),axis = 0)
print(a1)

[[1 2]
 [3 4]
 [6 7]
 [5 6]
 [7 8]]


In [27]:
a = np.array([1,2,3])
b = np.array([4,5,6])

result = np.vstack((a,b))

print(result)

[[1 2 3]
 [4 5 6]]


In [28]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])

result = np.hstack((a,b))

print(result)

[1 2 3 4 5 6 7]


In [29]:
jan = np.array([23,45,67])
feb = np.array([67,98,34])
mar = np.array([67,34,76])

qtr1 = np.vstack((jan,feb,mar))
print(qtr1)

[[23 45 67]
 [67 98 34]
 [67 34 76]]


In [30]:
qty_w1 = np.array([23,45,67])
qty_w2 = np.array([67,98,34])
qty_w3 = np.array([67,34,76])

qty1 = np.hstack((qty_w1,qty_w2,qty_w3))
print(qty1)

[23 45 67 67 98 34 67 34 76]


In [31]:
qty_w1 = np.array([70,80,90,100,20,90,70]).reshape(-1,1)
qty_w2 = np.array([70,80,90,100,20,90,70]).reshape(-1,1)
qty_w3 = np.array([70,80,90,100,20,90,70]).reshape(-1,1)
qty_w4 = np.array([70,80,90,100,20,90,70]).reshape(-1,1)
overall_inventory = np.hstack((qty_w1,qty_w2,qty_w3,qty_w4))
print(overall_inventory)

[[ 70  70  70  70]
 [ 80  80  80  80]
 [ 90  90  90  90]
 [100 100 100 100]
 [ 20  20  20  20]
 [ 90  90  90  90]
 [ 70  70  70  70]]


In [32]:
overall_inventory.shape

(7, 4)

In [34]:
ids = np.array([101,102,103]).reshape(-1,1)
salary = np.array([50000,65000,72000]).reshape(-1,1)
experiance = np.array([3,5,7]).reshape(-1,1)
dataset = np.hstack((ids,salary,experiance))
print(dataset)

[[  101 50000     3]
 [  102 65000     5]
 [  103 72000     7]]


In [35]:
ids = np.array([101,102,103])
salary = np.array([50000,65000,72000])
experiance = np.array([3,5,7])

df1 = np.column_stack((ids,salary,experiance))
print(df1)

[[  101 50000     3]
 [  102 65000     5]
 [  103 72000     7]]


In [38]:
quantity = np.array([2,5,3,4])
price = np.array([100,200,150,300])
revenue = quantity*price
df2 = np.column_stack((quantity,price,revenue))
print(df2)

[[   2  100  200]
 [   5  200 1000]
 [   3  150  450]
 [   4  300 1200]]


In [39]:
# Consider the following daily prices:

prices = np.array([
    820, 835, 810, 850, 875,
    860, 890, 910, 895, 930,
    945, 920, 960, 975, 990
])

# Calculate the change between consecutive days.
# Calculate absolute price movement.
# Find the largest movement.
# Find average movement.
# Find movements above average.
# Calculate percentage change between consecutive days.
# Round percentage changes to 2 decimals.
# Find days where price increased by more than 2%.
# Find maximum, minimum and range.
# Reshape prices into 3 x 5.
# Find average price of each row.

In [40]:
prices = np.array([
    820, 835, 810, 850, 875,
    860, 890, 910, 895, 930,
    945, 920, 960, 975, 990
])

In [41]:
# Calculate the change between consecutive days.
a = prices[1:]
print(a)

[835 810 850 875 860 890 910 895 930 945 920 960 975 990]


In [42]:
b = prices[:-1]
print(b)

[820 835 810 850 875 860 890 910 895 930 945 920 960 975]


In [45]:
ans = a-b
print(ans)

[ 15 -25  40  25 -15  30  20 -15  35  15 -25  40  15  15]


In [46]:
# Calculate absolute price movement.
abs_price = np.abs(ans)
print(abs_price)

[15 25 40 25 15 30 20 15 35 15 25 40 15 15]


In [47]:
# Find the largest movement.
largest_movement = np.max(ans)
print(largest_movement)

40


In [52]:
# Find average movement.
avg_mov = np.average(ans)
print(avg_mov)

12.142857142857142


In [54]:
# Find movements above average.
ans[ans > avg_mov]

array([15, 40, 25, 30, 20, 35, 15, 40, 15, 15])

In [55]:
# Calculate percentage change between consecutive days.
percentage = (ans / b) * 100
print("Percentage change:", percentage)

Percentage change: [ 1.82926829 -2.99401198  4.9382716   2.94117647 -1.71428571  3.48837209
  2.24719101 -1.64835165  3.91061453  1.61290323 -2.64550265  4.34782609
  1.5625      1.53846154]


In [56]:
# Round percentage changes to 2 decimals.
percentage = np.round(percentage, 2)
print("Rounded percentage:", percentage)

Rounded percentage: [ 1.83 -2.99  4.94  2.94 -1.71  3.49  2.25 -1.65  3.91  1.61 -2.65  4.35
  1.56  1.54]


In [57]:
# Find days where price increased by more than 2%.
above_2 = percentage > 2
print("Increase above 2%:", above_2)

Increase above 2%: [False False  True  True False  True  True False  True False False  True
 False False]


In [59]:
# Find maximum, minimum and range.
maximum = np.max(prices)
minimum = np.min(prices)
price_range = maximum - minimum
print("Maximum:", maximum)
print("Minimum:", minimum)
print("Range:", price_range)

Maximum: 990
Minimum: 810
Range: 180


In [60]:
# Reshape prices into 3 x 5.
prices_3x5 = prices.reshape(3, 5)
print("3 x 5:")
print(prices_3x5)

3 x 5:
[[820 835 810 850 875]
 [860 890 910 895 930]
 [945 920 960 975 990]]


In [61]:
# Find average price of each row.
row_average = np.mean(prices_3x5, axis=1)
print("Row averages:", row_average)

Row averages: [838. 897. 958.]
