In [1]:
import numpy as np

prices = np.array([
    820, 835, 810, 850, 875,
    860, 890, 910, 895, 930,
    945, 920, 960, 975, 990
])

# Calculate percentage change between consecutive days.
# Round percentage changes to 2 decimals.
# Find days where price increased by more than 2%.
# Find maximum, minimum and range.
# Reshape prices into 3 x 5.
# Find average price of each row.

In [2]:
# Calculate percentage change between consecutive days.
diff = prices[1:]-prices[:-1]
print(diff)

[ 15 -25  40  25 -15  30  20 -15  35  15 -25  40  15  15]


In [3]:
perc_change = (diff*100)/prices[:1]
print(perc_change)

[ 1.82926829 -3.04878049  4.87804878  3.04878049 -1.82926829  3.65853659
  2.43902439 -1.82926829  4.26829268  1.82926829 -3.04878049  4.87804878
  1.82926829  1.82926829]


In [4]:
# Round percentage changes to 2 decimals.
round_perc = np.round(perc_change,2)
print(round_perc)

[ 1.83 -3.05  4.88  3.05 -1.83  3.66  2.44 -1.83  4.27  1.83 -3.05  4.88
  1.83  1.83]


In [5]:
# Find days where price increased by more than 2%.
high_change_day = np.where(perc_change > 2,"Yes","No")
print(high_change_day)

['No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes' 'No'
 'No']


In [6]:
# Find maximum, minimum and range.
max_change = np.max(perc_change)
min_change = np.min(perc_change)
range_perc_change = max_change - min_change

print("max_change:", max_change)
print("min_change:", min_change)
print("range:", range_perc_change)

max_change: 4.878048780487805
min_change: -3.048780487804878
range: 7.926829268292683


In [7]:
# Reshape prices into 3 x 5.
new_prices = prices.reshape((3,5))
print(new_prices)

[[820 835 810 850 875]
 [860 890 910 895 930]
 [945 920 960 975 990]]


In [8]:
# Find average price of each row.
avg_price = np.mean(new_prices,axis=1)
print(avg_price)

[838. 897. 958.]


In [9]:
# A company records leads generated by four campaigns across five channels:

leads = np.array([
    [12000, 15000, 11000, 18000, 21000],
    [14000, 13000, 17000, 19000, 22000],
    [10000, 16000, 15000, 20000, 23000],
    [18000, 17000, 19000, 21000, 25000]
])

# Find total leads generated by each campaign.
# Find total leads generated by each channel.
# Find the campaign with maximum leads.
# Find the channel with maximum leads.

In [10]:
# Find total leads generated by each campaign.
total_each_compain = np.sum(leads,axis=1)
print(total_each_compain)

[ 77000  85000  84000 100000]


In [11]:
# Find total leads generated by each channel.
total_each_channel = np.sum(leads,axis=0)
print(total_each_channel)

[54000 61000 62000 78000 91000]


In [12]:
# Find the campaign with maximum leads.
compain_id = np.argmax(total_each_compain)+1
print(compain_id)

4


In [13]:
# Find the channel with maximum leads.
channel_id= np.argmax(total_each_channel)+1
print(channel_id)

5


In [14]:
# Find average leads per campaign.
# Find values above overall average.
# Increase values below 15,000 by 10%.
# Round the resulting values.
# Categorize values above median as "High" and others as "Low".
# Extract every second channel.

In [15]:
# Find average leads per campaign.
avg_compain = np.mean(total_each_compain)
print(avg_compain)

86500.0


In [16]:
overall_avg = np.mean(leads)
print(overall_avg)

17300.0


In [17]:
# Find values above overall average.

high_leads = leads[leads > overall_avg]
print(high_leads)

[18000 21000 19000 22000 20000 23000 18000 19000 21000 25000]


In [18]:
# Increase values below 15,000 by 10%.
new_leads = np.where(leads< 15000,leads*1.10,leads)
print(new_leads)

[[13200. 15000. 12100. 18000. 21000.]
 [15400. 14300. 17000. 19000. 22000.]
 [11000. 16000. 15000. 20000. 23000.]
 [18000. 17000. 19000. 21000. 25000.]]


In [19]:
# Round the resulting values.
round_result = np.round(new_leads)
print(round_result)

[[13200. 15000. 12100. 18000. 21000.]
 [15400. 14300. 17000. 19000. 22000.]
 [11000. 16000. 15000. 20000. 23000.]
 [18000. 17000. 19000. 21000. 25000.]]


In [20]:
# Categorize values above median as "High" and others as "Low".
median_lead = np.median(leads)
caterize = np.where(leads > median_lead,"High","Low" )
print(caterize)

[['Low' 'Low' 'Low' 'High' 'High']
 ['Low' 'Low' 'Low' 'High' 'High']
 ['Low' 'Low' 'Low' 'High' 'High']
 ['High' 'Low' 'High' 'High' 'High']]


In [21]:
# Extract every second channel.
channels = leads[:,1::2]
print(channels)

[[15000 18000]
 [13000 19000]
 [16000 20000]
 [17000 21000]]


In [22]:
jan = np.array([
    [101,5000],
    [102,7000],
    [103,4500]
])

feb = np.array([
    [104,6200],
    [105,8100],
    [106,5300]
])

In [23]:
sales_data = np.vstack((jan,feb))
print(sales_data)

[[ 101 5000]
 [ 102 7000]
 [ 103 4500]
 [ 104 6200]
 [ 105 8100]
 [ 106 5300]]


In [24]:
sales_data = np.hstack((jan,feb))
print(sales_data)

[[ 101 5000  104 6200]
 [ 102 7000  105 8100]
 [ 103 4500  106 5300]]


splitting arrays

In [25]:
numbers = np.array([
    10,20,30,40,
    50,60,80,80])

In [26]:
numbers[:4]

array([10, 20, 30, 40])

In [27]:
numbers[4:]

array([50, 60, 80, 80])

In [28]:
# syntax==> np.split(array, no_of_splits)

In [29]:
parts = np.split(numbers,2)
print(parts)

[array([10, 20, 30, 40]), array([50, 60, 80, 80])]


In [30]:
n1 = parts[0]
n2 = parts[1]
print(n1)
print(n2)

[10 20 30 40]
[50 60 80 80]


In [31]:
numbers = np.array([
    10,20,30,40,
    50,60,80,80])
parts = np.split(numbers,4)
n1 = parts[0]
n2 = parts[1]
n3 = parts[2]
n4 = parts[3]
print(n1)
print(n2)
print(n3)
print(n4)

[10 20]
[30 40]
[50 60]
[80 80]


In [32]:
for p in parts:
  print(p)

[10 20]
[30 40]
[50 60]
[80 80]


In [33]:
print(parts[0])

[10 20]


In [34]:
print(parts[1])

[30 40]


In [35]:
print(parts[2])

[50 60]


In [36]:
numbers = np.array([
    10,20,30,40,
    50,60,80,80])
parts = np.split(numbers,[2,5])
parts

[array([10, 20]), array([30, 40, 50]), array([60, 80, 80])]

In [37]:
parts = np.split(numbers,[3,5])
parts

[array([10, 20, 30]), array([40, 50]), array([60, 80, 80])]

In [38]:
data = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])

In [39]:
parts = np.split(data,2,axis=0)
parts

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [40]:
parts = np.split(data,2,axis=1)
parts

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [42]:
data = np.arange(1,21).reshape(10,2)
print(data)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [ ]:
# First 8 row--> training data
# Last two rows --->Tested data

In [43]:
train_data = data[:8]
test_data = data[-2:]

In [44]:
print(train_data)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [45]:
print(test_data)

[[17 18]
 [19 20]]


In [46]:
sales = np.array([
    120,135,128,
    145,150,160,
    155,170,165,
    180,190,200
])

# extract 4 quarters sales from it

In [47]:
qtr_sales = np.split(sales,4)
print(qtr_sales)

[array([120, 135, 128]), array([145, 150, 160]), array([155, 170, 165]), array([180, 190, 200])]


In [54]:
# Consider the following e-commerce dataset:

orders = np.array([
    [101, 3, 1200, 4],
    [102, 5, 800, 3],
    [103, 2, 2500, 4],
    [104, 8, 450, 4],
    [105, 4, 1800, 3],
    [106, 6, 950, 4],
    [107, 3, 2200, 4],
    [108, 10, 600, 3],
    [109, 7, 1500, 4],
    [110, 2, 3000, 4],
    [111, 5, 750, 3],
    [112, 9, 1250, 4]
])

# Order_ID
# Quantity
# Price
# Rating

In [49]:
# Inspect dimensions, shape and size.
# Extract the first 5 orders.
# Extract the last 3 orders.
# Extract every second order.
# Calculate revenue for every order.

In [50]:
# Inspect dimensions, shape and size.
orders_shape = np.shape(orders)
print(orders_shape)

(12, 4)


In [51]:
orders_dimension = np.ndim(orders)
print(orders_dimension)

2


In [52]:
orders_size = np.size(orders)
print(orders_size)

48


In [55]:
# Extract the first 5 orders.
orders[:5]

array([[ 101,    3, 1200,    4],
       [ 102,    5,  800,    3],
       [ 103,    2, 2500,    4],
       [ 104,    8,  450,    4],
       [ 105,    4, 1800,    3]])

In [56]:
# Extract the last 3 orders.
orders[-3:]

array([[ 110,    2, 3000,    4],
       [ 111,    5,  750,    3],
       [ 112,    9, 1250,    4]])

In [58]:
# Extract every second order.
orders[1::2]

array([[ 102,    5,  800,    3],
       [ 104,    8,  450,    4],
       [ 106,    6,  950,    4],
       [ 108,   10,  600,    3],
       [ 110,    2, 3000,    4],
       [ 112,    9, 1250,    4]])

In [57]:
# Calculate revenue for every order.
quantity = orders[:,1]
price = orders[:,2]
revenue = quantity * price
print(revenue)

[ 3600  4000  5000  3600  7200  5700  6600  6000 10500  6000  3750 11250]


In [ ]:
# calculate total and average revenue.
# Find the order with highest revenue.
# Calculate median revenue.

In [59]:
# calculate total and average revenue.
total_revenue = np.sum(revenue)
avg_revenue = np.mean(revenue)
print(total_revenue)
print(avg_revenue)

73200
6100.0


In [60]:
# Find the order with highest revenue.
orders[np.argmax(revenue)]

array([ 112,    9, 1250,    4])

In [61]:
# Calculate median revenue.
median_revenue = np.median(revenue)
print(median_revenue)

5850.0


In [ ]:
# Categorize orders:
# Revenue >= 15,000 → High
# Revenue >= 7,500 → Medium
# Otherwise → Low

# Find orders where quantity >= 5 AND rating >= 4.5.

# Find orders where price is above median OR rating is below 4.

# Give 10% discount to products whose price is above ₹1,000.

In [63]:
# Categorize orders:
# Revenue >= 15,000 → High
# Revenue >= 7,500 → Medium
# Otherwise → Low

criteria = np.where(revenue>= 15000,"High",np.where(revenue >= 7500,"Medium","Low"))
print(criteria)

['Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Medium' 'Low' 'Low'
 'Medium']


In [66]:
# Find orders where quantity >= 5 AND rating >= 4.5.
rating = orders[:, -1]
high_order = (quantity >= 5) & (rating >= 4.5)
print(high_order)
orders[high_order]

[False False False False False False False False False False False False]


array([], shape=(0, 4), dtype=int64)

In [68]:
# Find orders where price is above median OR rating is below 4.
median_sales = np.median(sales)
new_orders = (price > median_sales) | (rating < 4)
print(new_orders)
orders[new_orders]


[ True  True  True  True  True  True  True  True  True  True  True  True]


array([[ 101,    3, 1200,    4],
       [ 102,    5,  800,    3],
       [ 103,    2, 2500,    4],
       [ 104,    8,  450,    4],
       [ 105,    4, 1800,    3],
       [ 106,    6,  950,    4],
       [ 107,    3, 2200,    4],
       [ 108,   10,  600,    3],
       [ 109,    7, 1500,    4],
       [ 110,    2, 3000,    4],
       [ 111,    5,  750,    3],
       [ 112,    9, 1250,    4]])

In [71]:
# Give 10% discount to products whose price is above ₹1,000.
discount_10 = np.where(price > 10000, price*0.9, price )
print(discount_10)

[1200.  800. 2500.  450. 1800.  950. 2200.  600. 1500. 3000.  750. 1250.]


In [73]:
print(orders)

[[ 101    3 1200    4]
 [ 102    5  800    3]
 [ 103    2 2500    4]
 [ 104    8  450    4]
 [ 105    4 1800    3]
 [ 106    6  950    4]
 [ 107    3 2200    4]
 [ 108   10  600    3]
 [ 109    7 1500    4]
 [ 110    2 3000    4]
 [ 111    5  750    3]
 [ 112    9 1250    4]]
