In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [5]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [7]:
np.random.randint(1,100,10)

array([13, 18, 41, 24, 55, 42, 47, 80, 10,  1])

In [8]:
np.random.randint(1,100,10)

array([30, 49, 33, 26, 88, 15, 64, 40, 62, 67])

In [9]:
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [10]:
arr.ndim

1

In [11]:
arr.shape

(5,)

In [12]:
arr.size

5

In [13]:
arr.dtype

dtype('int64')

In [14]:
data = np.array([
    [10,20,30],
    [40,50,60]
])

print(data.ndim)
print(data.shape)
print(data.size)
print(data.dtype)

2
(2, 3)
6
int64


In [15]:
arr[0]

np.int64(10)

In [16]:
arr[1]

np.int64(20)

In [17]:
data[0,2]

np.int64(30)

In [18]:
arr[1:4]

array([20, 30, 40])

In [19]:
arr[:3]

array([10, 20, 30])

In [20]:
arr[2:]

array([30, 40, 50])

In [21]:
arr[::2]

array([10, 30, 50])

In [22]:
arr[::-1]

array([50, 40, 30, 20, 10])

In [23]:
arr

array([10, 20, 30, 40, 50])

In [24]:
data[:2,:2]

array([[10, 20],
       [40, 50]])

In [25]:
data[:,:2]

array([[10, 20],
       [40, 50]])

In [26]:
data[1:, 1:]

array([[50, 60]])

In [27]:
a = np.array([10,20,30])
b = np.array([1,2,3])
a*b

array([10, 40, 90])

In [28]:
a+b

array([11, 22, 33])

In [29]:
b = np.sqrt(arr)
b

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [30]:
np.abs(arr)

array([10, 20, 30, 40, 50])

In [31]:
np.square(arr)

array([ 100,  400,  900, 1600, 2500])

In [32]:
np.power(arr,2)

array([ 100,  400,  900, 1600, 2500])

In [33]:
np.round(b,2)

array([3.16, 4.47, 5.48, 6.32, 7.07])

In [34]:
np.floor(b)

array([3., 4., 5., 6., 7.])

In [35]:
np.ceil(b)

array([4., 5., 6., 7., 8.])

In [36]:
arr

array([10, 20, 30, 40, 50])

In [37]:
np.exp(arr) #// e^x , e = euler`s number ==> 2.72

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21])

In [38]:
np.log(arr)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301])

In [39]:
np.log10(arr)

array([1.        , 1.30103   , 1.47712125, 1.60205999, 1.69897   ])

In [40]:
np.sum(arr)

np.int64(150)

In [41]:
np.mean(arr)

np.float64(30.0)

In [42]:
np.median(arr)

np.float64(30.0)

In [43]:
np.min(arr)

np.int64(10)

In [44]:
np.max(arr)

np.int64(50)

In [45]:
np.std(arr)

np.float64(14.142135623730951)

In [46]:
np.var(arr)

np.float64(200.0)

In [47]:
np.percentile(arr,75)

np.float64(40.0)

In [48]:
np.argmax(arr)

np.int64(4)

In [49]:
np.argmin(arr)

np.int64(0)

In [50]:
sales = np.array([
    [100,200,300],
    [150,150,350],
    [200,300,400]
])

In [51]:
np.sum(sales,axis=1)

array([600, 650, 900])

In [52]:
np.sum(sales,axis=0)

array([ 450,  650, 1050])

In [53]:
marks = np.array([45,72,88,35,91,65])
marks[marks >= 50]

array([72, 88, 91, 65])

In [54]:
marks[(marks >= 50) & (marks <= 80)]

array([72, 65])

In [55]:
marks[(marks < 40) | (marks > 90)]

array([35, 91])

In [56]:
marks[~(marks > 50)]

array([45, 35])

In [57]:
np.where(marks >=90,"Excellent",np.where(marks>=50,"Pass","Fail"))

array(['Fail', 'Pass', 'Pass', 'Fail', 'Excellent', 'Pass'], dtype='<U9')

In [58]:
arr = np.arange(1,13)
matrix = arr.reshape(3,4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [59]:
matrix = arr.reshape(3,-1)
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
matrix.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [62]:
a = np.array([
    [1,2],
    [3,4]
])

b = np.array([
    [5,6],
    [7,8]
])

In [63]:
vertical = np.vstack((a,b))
vertical

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [64]:
np.shape(vertical)

(4, 2)

In [65]:
horizontal = np.hstack((a,b))
horizontal

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [66]:
np.shape(horizontal)

(2, 4)

In [67]:
arr = np.arange(1,13)
np.split(arr,3)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

In [68]:
np.random.seed(42)

numbers = np.random.randint(1,100,10)
print(numbers)

[52 93 15 72 61 21 83 87 75 75]


In [69]:
np.random.seed(42)

numbers = np.random.randint(1,100,10)
print(numbers)

[52 93 15 72 61 21 83 87 75 75]


In [70]:
np.random.random(5)

array([0.86617615, 0.60111501, 0.70807258, 0.02058449, 0.96990985])

In [71]:
np.random.uniform(10,50,5)

array([43.29770563, 18.49356443, 17.27299869, 17.33618039, 22.16968972])

In [72]:
np.random.choice([10,20,30],5)

array([20, 10, 10, 10, 30])

In [73]:
# Task: create a dataset having the following columns:
# order_id
# quantity,
# unit_price,
# discount,
# rating

# with 20 rows

In [74]:
np.random.seed(100)
order_id = np.arange(1,21)
order_id

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [75]:
quantity = np.random.randint(1,11,20)
quantity

array([ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3,  3,  3,  2,  1,  9,  5,  1,
       10,  7,  3])

In [76]:
unit_price = np.random.randint(500,2000,20)
unit_price

array([ 915, 1397, 1665, 1257, 1112, 1528, 1103, 1335,  635,  549, 1955,
        817, 1282, 1467, 1263, 1860,  502, 1389, 1117,  978])

In [78]:
discount = np.random.randint(0,36,20)
discount

array([19, 34, 27, 30, 18,  0, 34, 10, 17,  8, 13, 30, 17,  4, 27, 27, 19,
       14,  0, 13])

In [79]:
rating = np.random.randint(1,6,20)
rating

array([2, 5, 3, 4, 4, 5, 3, 5, 4, 2, 1, 5, 4, 5, 3, 3, 5, 3, 5, 2])

In [80]:
dataset = np.column_stack((order_id,quantity,unit_price,discount,rating))
dataset

array([[   1,    9,  915,   19,    2],
       [   2,    9, 1397,   34,    5],
       [   3,    4, 1665,   27,    3],
       [   4,    8, 1257,   30,    4],
       [   5,    8, 1112,   18,    4],
       [   6,    1, 1528,    0,    5],
       [   7,    5, 1103,   34,    3],
       [   8,    3, 1335,   10,    5],
       [   9,    6,  635,   17,    4],
       [  10,    3,  549,    8,    2],
       [  11,    3, 1955,   13,    1],
       [  12,    3,  817,   30,    5],
       [  13,    2, 1282,   17,    4],
       [  14,    1, 1467,    4,    5],
       [  15,    9, 1263,   27,    3],
       [  16,    5, 1860,   27,    3],
       [  17,    1,  502,   19,    5],
       [  18,   10, 1389,   14,    3],
       [  19,    7, 1117,    0,    5],
       [  20,    3,  978,   13,    2]])

In [81]:
quantity = dataset[:,1]
unit_price = dataset[:,2]
revenue = quantity*unit_price
revenue

array([ 8235, 12573,  6660, 10056,  8896,  1528,  5515,  4005,  3810,
        1647,  5865,  2451,  2564,  1467, 11367,  9300,   502, 13890,
        7819,  2934])

In [82]:
dataset = np.column_stack((dataset,revenue))
dataset

array([[    1,     9,   915,    19,     2,  8235],
       [    2,     9,  1397,    34,     5, 12573],
       [    3,     4,  1665,    27,     3,  6660],
       [    4,     8,  1257,    30,     4, 10056],
       [    5,     8,  1112,    18,     4,  8896],
       [    6,     1,  1528,     0,     5,  1528],
       [    7,     5,  1103,    34,     3,  5515],
       [    8,     3,  1335,    10,     5,  4005],
       [    9,     6,   635,    17,     4,  3810],
       [   10,     3,   549,     8,     2,  1647],
       [   11,     3,  1955,    13,     1,  5865],
       [   12,     3,   817,    30,     5,  2451],
       [   13,     2,  1282,    17,     4,  2564],
       [   14,     1,  1467,     4,     5,  1467],
       [   15,     9,  1263,    27,     3, 11367],
       [   16,     5,  1860,    27,     3,  9300],
       [   17,     1,   502,    19,     5,   502],
       [   18,    10,  1389,    14,     3, 13890],
       [   19,     7,  1117,     0,     5,  7819],
       [   20,     3,   978,   

In [83]:
campaigns = np.array([
    [101, 10000, 800, 80, 5000, 7500],
    [102, 15000, 1200, 150, 7000, 12000],
    [103, 8000, 400, 30, 3000, 4200],
    [104, 20000, 1800, 250, 9000, 18000],
    [105, 12000, 600, 90, 6000, 8000],
    [106, 18000, 1500, 220, 8000, 16000],
    [107, 9000, 300, 20, 2500, 3000],
    [108, 25000, 2200, 300, 11000, 24000]
])

In [ ]:
# Campaign_ID
# Impressions
# Clicks
# Conversions
# Cost
# Revenue

In [ ]:
# CTR = Clicks / Impressions * 100

# Conversion Rate = Conversions / Clicks * 100

# ROI = (Revenue - Cost) / Cost * 100

In [ ]:
# Find highest-revenue campaign.
# Find highest-ROI campaign.
# Calculate average CTR.
# Calculate average ROI.
# Find campaigns with above-average CTR and ROI.

In [94]:
# Find highest-revenue campaign.
Revenue = campaigns[:,-1]
Revenue
np.argmax(Revenue)
campaigns[7]

array([  108, 25000,  2200,   300, 11000, 24000])

In [97]:
# Find highest-ROI campaign.
ROI = (Revenue - Cost) / Cost * 100
ROI

array([ 50.        ,  71.42857143,  40.        , 100.        ,
        33.33333333, 100.        ,  20.        , 118.18181818])

In [95]:
Cost = campaigns[:,-2]
Cost

array([ 5000,  7000,  3000,  9000,  6000,  8000,  2500, 11000])

In [100]:
# Calculate average CTR.
CTR = Clicks / Impressions * 100
CTR

array([8.        , 8.        , 5.        , 9.        , 5.        ,
       8.33333333, 3.33333333, 8.8       ])

In [98]:
Clicks = campaigns[:,2]
Impressions = campaigns[:,1]

In [102]:
avg_CTR = np.mean(CTR)
avg_CTR

np.float64(6.933333333333334)

In [103]:
# Calculate average ROI.
avg_ROI = np.mean(ROI)
avg_ROI

np.float64(66.61796536796537)

In [105]:
# Find campaigns with above-average CTR and ROI.
Criteria = (CTR > avg_CTR) & (ROI > avg_ROI)
campaigns[Criteria]

array([[  102, 15000,  1200,   150,  7000, 12000],
       [  104, 20000,  1800,   250,  9000, 18000],
       [  106, 18000,  1500,   220,  8000, 16000],
       [  108, 25000,  2200,   300, 11000, 24000]])