In [ ]:
import numpy as np
# A bank account has the following transactions:
transactions = np.array([
5000, -2000, 15000, -4500, 7000,
-12000, 25000, -3000, 8000, -18000,
4500, 22000, -6000, 9000, -2500
])
# Positive values represent deposits and negative values represent withdrawals

In [ ]:
# Extract deposits.
# Extract withdrawals.
# Calculate total deposits and withdrawals.
# Calculate net transaction amount.
# Calculate absolute transaction values.

In [ ]:
# Extract deposits.
deposites = transactions[transactions > 0]
print(deposites)

[ 5000 15000  7000 25000  8000  4500 22000  9000]


In [ ]:
# Extract withdrawals.
withdrawals = transactions[transactions < 0]
print(withdrawals)

[ -2000  -4500 -12000  -3000 -18000  -6000  -2500]


In [ ]:
# Calculate total deposits and withdrawals.
print(np.sum(deposites))
print(np.sum(withdrawals))

95500
-48000


In [ ]:
# Calculate net transaction amount.
total_transactions = np.sum(transactions)
print(total_transactions)

47500


In [ ]:
# Calculate absolute transaction values.
absolute = np.abs(transactions)
print(absolute)

[ 5000  2000 15000  4500  7000 12000 25000  3000  8000 18000  4500 22000
  6000  9000  2500]


In [ ]:
# Find transactions whose absolute value is above the average absolute transaction.
# Find the largest deposit.
# Find the largest withdrawal
# Create labels Credit and Debit
# Find percentage of transactions whose absolute value is greater than ₹10,000.
# Reshape the data into 3 × 5.
# Calculate total transaction value for each row

In [ ]:
# Find transactions whose absolute value is above the average absolute transaction.
avg_absolute = np.average(absolute)
absolute[absolute > avg_absolute]

array([15000, 12000, 25000, 18000, 22000])

In [ ]:
# Find the largest deposit.
lar_deposite = np.max(deposites)
print(lar_deposite)

25000


In [ ]:
# Find the largest withdrawal
lar_withdrawl = np.max(withdrawals)
print(lar_withdrawl)

-2000


In [ ]:
# Create labels "Credit" and "Debit"
print(np.where(transactions > 0,"Credit","Debit" ))

['Credit' 'Debit' 'Credit' 'Debit' 'Credit' 'Debit' 'Credit' 'Debit'
 'Credit' 'Debit' 'Credit' 'Credit' 'Debit' 'Credit' 'Debit']


In [ ]:
# Find percentage of transactions whose absolute value is greater than ₹10,000.
abs_t = np.abs(transactions)
abs10k = abs_t[abs_t > 10000]
print(abs10k)


[15000 12000 25000 18000 22000]


In [ ]:
m = len(abs10k)
n = len(abs_t)
perc = m*100/n
print(perc)

33.333333333333336


In [ ]:
# Reshape the data into 3 × 5.
new_t = transactions.reshape(3,5)
print(new_t)

[[  5000  -2000  15000  -4500   7000]
 [-12000  25000  -3000   8000 -18000]
 [  4500  22000  -6000   9000  -2500]]


In [ ]:
# Calculate total transaction value for each row
print(np.sum(new_t, axis=1))

[20500     0 27000]


In [ ]:
# A factory has four machines operating for six days:
# production = np.array([
# [120, 135, 128, 145, 150, 138],
# [110, 125, 118, 130, 142, 135],
# [160, 155, 170, 165, 180, 175],
# [95, 105, 100, 115, 108, 120]
#                         ])

# Calculate total production by machine.
# Calculate total production by day.
# Calculate average production of each machine.
# Find the machine with the highest average production.
# Find the day with the lowest production.

In [ ]:
production = np.array([
[120, 135, 128, 145, 150, 138],
[110, 125, 118, 130, 142, 135],
[160, 155, 170, 165, 180, 175],
[95, 105, 100, 115, 108, 120]
                        ])

In [ ]:
# Calculate total production by machine.
total_production = np.sum(production,axis=1)
print(total_production)

[ 816  760 1005  643]


In [ ]:
# Calculate total production by day.
oneday_total_prd = np.sum(production,axis=0)
print(oneday_total_prd)

[485 520 516 555 580 568]


In [ ]:
# Calculate average production of each machine.
avg_prd = np.average(production,axis=1)
print(avg_prd)

[136.         126.66666667 167.5        107.16666667]


In [ ]:
# Find the machine with the highest average production.
ind = np.argmax(avg_prd)
print(ind)

2


In [ ]:
production[2]

array([160, 155, 170, 165, 180, 175])

In [ ]:
# Find the day with the lowest production.
np.argmin(oneday_total_prd)

np.int64(0)

In [ ]:
# Find values above the overall average.
# Increase production values below 120 by 5%.
# Extract alternate days.
# Extract the last 3 days for machines 1 and 3.
# Create "High" and "Normal" labels based on the overall average

In [ ]:
# Find values above the overall average.
avg_production = np.average(production)
print(avg_production)

134.33333333333334


In [ ]:
# Increase production values below 120 by 5%.
production = np.where(production < 120 ,production*1.05,production)
print(production)

[[120.   135.   128.   145.   150.   138.  ]
 [115.5  125.   123.9  130.   142.   135.  ]
 [160.   155.   170.   165.   180.   175.  ]
 [ 99.75 110.25 105.   120.75 113.4  120.  ]]


In [ ]:
# Extract alternate days.
print(production[:,::2])

[[120.   128.   150.  ]
 [115.5  123.9  142.  ]
 [160.   170.   180.  ]
 [ 99.75 105.   113.4 ]]


In [ ]:
# Extract the last 3 days for machines 1 and 3.
print(production[[0,2],-3:])

[[145. 150. 138.]
 [165. 180. 175.]]


In [ ]:
# Create "High" and "Normal" labels based on the overall average
np.where(production > avg_production,"High","Normal")

array([['Normal', 'High', 'Normal', 'High', 'High', 'High'],
       ['Normal', 'Normal', 'Normal', 'Normal', 'High', 'High'],
       ['High', 'High', 'High', 'High', 'High', 'High'],
       ['Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal']],
      dtype='<U6')

In [ ]:
# Consider the following loan portfolio:
# loan_amount = np.array([
# 100000, 250000, 500000, 750000,
# 120000, 350000, 900000, 450000
# ])
# interest_rate = np.array([
# 8.5, 9.2, 8.8, 10.1,
# 7.9, 9.5, 10.5, 8.7
# ])
# Calculate annual interest for every loan.
# Calculate total interest.
# Calculate average interest.
# Find the loan generating the highest interest.
# Find loans above ₹400,000 with interest rate above 9%

In [ ]:
loan_amount = np.array([
100000, 250000, 500000, 750000,
120000, 350000, 900000, 450000
])
interest_rate = np.array([
8.5, 9.2, 8.8, 10.1,
7.9, 9.5, 10.5, 8.7
])

In [ ]:
# Calculate annual interest for every loan.
annual_intrest = loan_amount*interest_rate/100
print(annual_intrest)

[ 8500. 23000. 44000. 75750.  9480. 33250. 94500. 39150.]


In [ ]:
# Calculate total interest.
total_intrest = np.sum(annual_intrest)
print(total_intrest)

327630.0


In [ ]:
# Calculate average interest.
avg_intrest = np.average(annual_intrest)
print(avg_intrest)

40953.75


In [ ]:
# Find the loan generating the highest interest.
high_ind = np.argmax(annual_intrest)
print(high_ind)

6


In [ ]:
# Find loans above ₹400,000 with interest rate above 9%
critaria = (loan_amount > 400000) & (interest_rate > 9)
print(critaria)
loan_amount[critaria]

[False False False  True False False  True False]


array([750000, 900000])