In [1]:
# # A factory collects temperatures from 20 sensor readings:
# temperature = np.array([
# 28.5, 31.2, 29.8, 35.6, 38.1,
# 40.2, 27.9, 30.5, 42.3, 39.8,
# 36.4, 33.2, 29.1, 41.7, 44.2,
# 31.8, 34.5, 37.6, 26.9, 43.1
# ])
# Calculate mean, median, minimum and maximum.
# Calculate variance and standard deviation.
# Find all temperatures more than one standard deviation above the mean.
# Calculate the absolute difference between every temperature and the mean.
# Find the five readings having the largest deviation from the mean.
# Round all temperatures to the nearest whole number.

In [2]:
import numpy as np
temperature = np.array([
28.5, 31.2, 29.8, 35.6, 38.1,
40.2, 27.9, 30.5, 42.3, 39.8,
36.4, 33.2, 29.1, 41.7, 44.2,
31.8, 34.5, 37.6, 26.9, 43.1
])

In [3]:
temperature.ndim

1

In [4]:
temperature.shape

(20,)

In [5]:
temperature.size

20

In [6]:
# Calculate mean, median, minimum and maximum.
temp_mean = np.mean(temperature)
temp_mean

np.float64(35.12)

In [7]:
mediant = np.median(temperature)
mediant

np.float64(35.05)

In [8]:
temp_min = np.min(temperature)
temp_mean

np.float64(35.12)

In [9]:
temp_max = np.max(temperature)
temp_max

np.float64(44.2)

In [10]:
# Calculate variance and standard deviation.
std_temp = np.std(temperature)
std_temp

np.float64(5.410415880503088)

In [11]:
var = np.square(std_temp)
var

np.float64(29.2726)

In [12]:
# Find all temperatures more than one standard deviation above the mean.
new_t = temperature[temperature >(temp_mean + std_temp) ]
new_t

array([42.3, 41.7, 44.2, 43.1])

In [13]:
np.where(temperature > (temp_mean + std_temp),"Yes","No")

array(['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No',
       'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes'],
      dtype='<U3')

In [14]:
# Calculate the absolute difference between every temperature and the mean.
deviation = np.abs(temperature-temp_mean)
deviation

array([6.62, 3.92, 5.32, 0.48, 2.98, 5.08, 7.22, 4.62, 7.18, 4.68, 1.28,
       1.92, 6.02, 6.58, 9.08, 3.32, 0.62, 2.48, 8.22, 7.98])

In [15]:
# Find the five readings having the largest deviation from the mean.
largest_deviation  = np.sort(deviation)
largest_deviation

array([0.48, 0.62, 1.28, 1.92, 2.48, 2.98, 3.32, 3.92, 4.62, 4.68, 5.08,
       5.32, 6.02, 6.58, 6.62, 7.18, 7.22, 7.98, 8.22, 9.08])

In [16]:
largest_deviation[-5:]

array([7.18, 7.22, 7.98, 8.22, 9.08])

In [17]:
# Round all temperatures to the nearest whole number.
np.round(temperature,2)

array([28.5, 31.2, 29.8, 35.6, 38.1, 40.2, 27.9, 30.5, 42.3, 39.8, 36.4,
       33.2, 29.1, 41.7, 44.2, 31.8, 34.5, 37.6, 26.9, 43.1])

In [18]:
# Categorize temperatures:
# >= 40 → "Critical"
# >= 35 → "Warning"
# Otherwise → "Normal"
# Find the number and percentage of critical readings.
# Reshape the readings into a 4 × 5 array.
# Find the average temperature for each row

In [19]:
# Categorize temperatures:
# >= 40 → "Critical"
# >= 35 → "Warning"
# Otherwise → "Normal"
cat_t = np.where(temperature >= 40,"Critical",np.where(temperature>= 35,"Warning","Normal"))
cat_t

array(['Normal', 'Normal', 'Normal', 'Warning', 'Warning', 'Critical',
       'Normal', 'Normal', 'Critical', 'Warning', 'Warning', 'Normal',
       'Normal', 'Critical', 'Critical', 'Normal', 'Normal', 'Warning',
       'Normal', 'Critical'], dtype='<U8')

In [20]:
# Find the number and percentage of critical readings.
critical_t = cat_t[cat_t == "Critical"]

In [21]:
c = len(critical_t)
c

5

In [22]:
n = len(cat_t)
n

20

In [23]:
perc = c*100/n
perc

25.0

In [24]:
# Reshape the readings into a 4 × 5 array.
new_temp = temperature.reshape(4,5)
new_temp

array([[28.5, 31.2, 29.8, 35.6, 38.1],
       [40.2, 27.9, 30.5, 42.3, 39.8],
       [36.4, 33.2, 29.1, 41.7, 44.2],
       [31.8, 34.5, 37.6, 26.9, 43.1]])

In [25]:
# Find the average temperature for each row
np.average(new_temp,axis=1)

array([32.64, 36.14, 36.92, 34.78])

In [27]:
# Consider the following employee data:
# employees = np.array([
# [101, 42000, 3, 450000],
# [102, 65000, 6, 720000],
# [103, 38000, 2, 300000],
# [104, 90000, 8, 950000],
# [105, 55000, 5, 610000],
# [106, 72000, 7, 830000]
# ])
# Columns represent:
# Employee_ID
# Salary
# Experience
# Annual_Sales

# Extract salary, experience and annual sales.
# Calculate sales-to-salary ratio.
# Find the employee with the highest annual sales.
# Find employees having at least 5 years experience AND sales above ₹600,000.
# Calculate bonus:
# Sales >= ₹800,000 → 10%
# Sales >= ₹600,000 → 7%
# Otherwise → 3%

In [28]:
employees = np.array([
[101, 42000, 3, 450000],
[102, 65000, 6, 720000],
[103, 38000, 2, 300000],
[104, 90000, 8, 950000],
[105, 55000, 5, 610000],
[106, 72000, 7, 830000]
])

In [29]:
# Extract salary, experience and annual sales.
print(employees[:,-3:])

[[ 42000      3 450000]
 [ 65000      6 720000]
 [ 38000      2 300000]
 [ 90000      8 950000]
 [ 55000      5 610000]
 [ 72000      7 830000]]


In [33]:
# Calculate sales-to-salary ratio.
ratio = employees[:,-1]/employees[:,1]
np.round(ratio)

array([11., 11.,  8., 11., 11., 12.])

In [42]:
# Find the employee with the highest annual sales.
np.argmax(employees[:,-1])

np.int64(3)

In [31]:
# Find employees having at least 5 years experience AND sales above ₹600,000.
employees[:,2] & employees[:,-1] > 600000

array([False, False, False, False, False, False])

In [36]:
# Calculate bonus:
# Sales >= ₹800,000 → 10%
# Sales >= ₹600,000 → 7%
# Otherwise → 3%
bonus = np.where(employees[:,-1]>800000,employees[:,-1]*0.10,np.where(employees[:,-1]>=600000,employees[:,-1]*0.07,employees[:,-1]*0.03))
bonus

array([13500., 50400.,  9000., 95000., 42700., 83000.])

In [ ]:
# Calculate total bonus amount.
# Find average salary of employees receiving a 10% bonus.
# Find median salary.
# Find employees whose salary is above median salary but experience is less than 6 years.
# Round sales-to-salary ratio to 2 decimal places.

In [37]:
# Calculate total bonus amount.
np.sum(bonus)

np.float64(293600.0)

In [85]:
# Find average salary of employees receiving a 10% bonus.
# Employees receiving a 10% bonus are those with Annual_Sales >= ₹800,000.
bonus_10_percent_mask = employees[:,-1] >= 800000
salaries_for_10_percent_bonus = employees[bonus_10_percent_mask][:,1]
average_salary_10_percent_bonus = np.mean(salaries_for_10_percent_bonus)
average_salary_10_percent_bonus

np.float64(81000.0)

In [47]:
# Find median salary.
median_saley = np.median(employees[:,1])
print(median_saley)

60000.0


In [51]:
# Find employees whose salary is above median salary but experience is less than 6 years.
salary = employees[:,1]
experiance = employees[:,2]
(salary > median_saley) & (experiance < 6)

array([False, False, False, False, False, False])

In [52]:
# Round sales-to-salary ratio to 2 decimal places.
np.round(ratio,2)

array([10.71, 11.08,  7.89, 10.56, 11.09, 11.53])

In [54]:
# Consider the following 6 × 6 grayscale image:
# image = np.array([
# [10, 25, 40, 55, 70, 85],
# [20, 35, 50, 65, 80, 95],
# [30, 45, 60, 75, 90, 105],
# [40, 55, 70, 85, 100, 115],
# [50, 65, 80, 95, 110, 125],
# [60, 75, 90, 105, 120, 135]
# ])
# Find ndim, shape and size.
# Extract the central 4 × 4 region.
# Increase the central region by 20%
# Cap all pixel values above 100 at 100.
# Find mean, minimum and maximum pixel values

In [75]:
image = np.array([
[10, 25, 40, 55, 70, 85],
[20, 35, 50, 65, 80, 95],
[30, 45, 60, 75, 90, 105],
[40, 55, 70, 85, 100, 115],
[50, 65, 80, 95, 110, 125],
[60, 75, 90, 105, 120, 135]
])

In [76]:
# Find ndim, shape and size.
np.ndim(image)

2

In [77]:
np.shape(image)

(6, 6)

In [78]:
np.size(image)

36

In [79]:
# Extract the central 4 × 4 region.
new_image = image[1:5, 1:5]
new_image

array([[ 35,  50,  65,  80],
       [ 45,  60,  75,  90],
       [ 55,  70,  85, 100],
       [ 65,  80,  95, 110]])

In [90]:
# Increase the central region by 20%
image[1:5, 1:5] = image[1:5, 1:5]*1.2

In [91]:
image

array([[ 10,  25,  40,  55,  70,  85],
       [ 20,  42,  60,  78,  96,  95],
       [ 30,  54,  72,  90, 108, 105],
       [ 40,  66,  84, 102, 120, 115],
       [ 50,  78,  96, 114, 132, 125],
       [ 60,  75,  90, 105, 120, 135]])

In [97]:
# Cap all pixel values above 100 at 100.
image = np.where(image>100, 100,image )
image

array([[ 10,  25,  40,  55,  70,  85],
       [ 20,  42,  60,  78,  96,  95],
       [ 30,  54,  72,  90, 100, 100],
       [ 40,  66,  84, 100, 100, 100],
       [ 50,  78,  96, 100, 100, 100],
       [ 60,  75,  90, 100, 100, 100]])

In [98]:
# Find mean, minimum and maximum pixel values
np.mean(image)

np.float64(73.91666666666667)

In [99]:
np.min(image)

np.int64(10)

In [100]:
np.max(image)

np.int64(100)

In [ ]:
# Find pixels above the 75th percentile.
# Flatten the image.
# Find pixels below the overall mean.
# Reshape the flattened array back into 6 × 6.

In [101]:
# Find pixels above the 75th percentile.
p75 = np.percentile(image, 75)
p75

np.float64(100.0)

In [102]:
image[image > p75]

array([], dtype=int64)

In [103]:
#  Flatten the image.
image.flatten()

array([ 10,  25,  40,  55,  70,  85,  20,  42,  60,  78,  96,  95,  30,
        54,  72,  90, 100, 100,  40,  66,  84, 100, 100, 100,  50,  78,
        96, 100, 100, 100,  60,  75,  90, 100, 100, 100])

In [105]:
# Find pixels below the overall mean.
avg = np.mean(image)
image[image < avg]

array([10, 25, 40, 55, 70, 20, 42, 60, 30, 54, 72, 40, 66, 50, 60])

In [106]:
# Reshape the flattened array back into 6 × 6.
new_image = image.reshape(6,6)
new_image

array([[ 10,  25,  40,  55,  70,  85],
       [ 20,  42,  60,  78,  96,  95],
       [ 30,  54,  72,  90, 100, 100],
       [ 40,  66,  84, 100, 100, 100],
       [ 50,  78,  96, 100, 100, 100],
       [ 60,  75,  90, 100, 100, 100]])